### PR TITLE
Add API for testing type String for multi-blocks

### PR DESCRIPTION
**Pull request by dbsxdbsx**
Adding an API with type `String` for testing multi-blocks.  Since there are more and more features, to avoid potential issues when using multi-blocks, this API is essential, since `String` is quite a common type and not a built-in type for Dart and Rust, it can reflect issues quite common.

ps: the CI test may fail.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
LGTM after CI passes :)

**Comment by fzyzcjy** [comment]
👀

**Comment by dbsxdbsx** [comment]
> 👀
This pr is closed on purpose. I would try to fix issues related to multi-block in another pr.

**Comment by fzyzcjy** [comment]
I see. Take your time!

**Pull request closed without merging**
