### PR TITLE
Add flutter example for macOS and add macOS instructions in README

### PR DESCRIPTION
**Pull request by AlienKevin**

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Thanks for the code! Could you please add a few lines in the GitHub CI tests (e.g. near https://github.com/fzyzcjy/flutter_rust_bridge/blob/5c65b17be0a7c0322e7f422fc582690c893ab545/.github/workflows/ci.yaml#L181 ), such that we can be pretty sure in the future this feature does work ;)

**Comment by fzyzcjy** [comment]
@all-contributors please add @AlienKevin for code

**Comment by fzyzcjy** [comment]
@all-contributors please add @AlienKevin for code

**Comment by fzyzcjy** [comment]
@all-contributors please add @AlienKevin for code

**Comment by fzyzcjy** [comment]
@all-contributors please add @AlienKevin for code

**Comment by fzyzcjy** [comment]
do not worry that failed ci of android. with a re-run it will highly possibly be ok.

**Comment by AlienKevin** [comment]
I added the tests, but am not sure whether it works or not. Also, the macOS versions provided by GitHub workflow are limited to Big Sur 11 and Catalina 10.15. I have only tested on my Monterey 12, though it might at least work on Big Sur I hope.

**Comment by fzyzcjy** [comment]
> I added the tests, but am not sure whether it works or not. Also, the macOS versions provided by GitHub workflow are limited to Big Sur 11 and Catalina 10.15. I have only tested on my Monterey 12, though it might at least work on Big Sur I hope.

Thanks!

**Comment by AlienKevin** [comment]
The tests for macOS failed probably because the build failed. Are there any dependencies I missed?
```
[  +24 ms] ld: warning: directory not found for option '-L/Users/kevin/development/dart/flutter_rust_bridge/frb_example/with_flutter/rust/target/x86_64-apple-darwin/debug'
[   +1 ms] ld: library not found for -lflutter_rust_bridge_example
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +7 ms] ** BUILD FAILED **
[        ] The following build commands failed:
[        ] 	Ld /Users/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/MacOS/with_flutter normal (in target 'Runner' from project 'Runner')
[        ] (1 failure)
```

**Comment by fzyzcjy** [comment]
Hmm

> ld: warning: directory not found for option '-L/Users/kevin/development/dart/flutter_rust_bridge/frb_example/with_flutter/rust/target/x86_64-apple-darwin/debug'

What about use `ls` or similar commands to examine the whole `target` folder, then we can see whether it contains dylibs or not

**Comment by fzyzcjy** [comment]
In addition, when your script calls Rust's build system, try to make it verbose (e.g. `-vv`). Then you will see a lot of log about it.

**Comment by fzyzcjy** [comment]
When using your own computer, do you build the rust lib manually (before running `flutter run`)? If so maybe it is also needed in this CI script

**Comment by AlienKevin** [comment]
> When using your own computer, do you build the rust lib manually (before running `flutter run`)? If so maybe it is also needed in this CI script
I had to set up dylib config in Xcode and after that just do flutter run as usual.

**Comment by fzyzcjy** [comment]
> I'm not aware of any automated scripts that add a dylib to Xcode configuration so I have always done it manually in Xcode.

Then it may be caused by this? i.e. CI does not have this step.

**Comment by AlienKevin** [comment]
> > I'm not aware of any automated scripts that add a dylib to Xcode configuration so I have always done it manually in Xcode.
> 
> Then it may be caused by this? i.e. CI does not have this step.

Yeah, I'm pretty sure CI doesn't have this step. I saw that the Linux test case is temporarily disabled. Can we disable the macOS tests for now and merge the PR, since the steps involved are quite complicated?

**Comment by fzyzcjy** [comment]
All right...

**Comment by fzyzcjy** [comment]
@all-contributors please add @AlienKevin for doc

**Pull request merged**
