### PR TITLE
Fix geneartion of `async` functions when `default_dart_async: false` ; Update frb_example/integrate_third_party

### LINKED ISSUE #2167: A setter is not generated in class ScriptProcessorNode
### Describe the bug

In ```class PannerNode``` there is a simple getter not generated: 
```rust
#[derive(Debug)]
pub struct StereoPannerNode {
    /// Represents the node instance and its associated audio context
    registration: AudioContextRegistration,
    /// Infos about audio node channel configuration
    channel_config: ChannelConfig,
    /// The position of the input in the output’s stereo image. -1 represents
    /// full left, +1 represents full right.
    pan: AudioParam,
}

impl AudioNode for StereoPannerNode {
    ...
    /// Returns the pan audio parameter
    #[must_use]
    pub fn pan(&self) -> &AudioParam {
        &self.pan
    }
}
```

### Steps to reproduce

-

### Logs

```shell
-
```

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

_No response_

### LINKED ISSUE #2178: Geneartion of `async` functions when `default_dart_async: false`
### Describe the bug

When I set the parameter `default_dart_async: false` I get after, 10 errors.
Most of them are in class `Context` and `ContextOffline`.

For example : 
```rust
fn wire__web_audio_api__context__OfflineAudioContext_suspend_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "OfflineAudioContext_suspend",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OfflineAudioContext>,
            >>::sse_decode(&mut deserializer);
            let api_suspend_time = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok({
                    web_audio_api::context::OfflineAudioContext::suspend(
                        &*api_that_guard,
                        api_suspend_time,
                    )
                    .await;
                })?;
                Ok(output_ok)
            })())
        },
    )
}
```
The `await` almost at the end of the fn is NOK, because the function is not `async`.
I think the problem is tied with the declaration of `suspend()` in the WebAudioApi-RS : 
```rust
    pub async fn suspend(&self, suspend_time: f64) {
```
Probably that our generated fn should be `async` too
```rust
fn wire__web_audio_api__context__OfflineAudioContext_suspend_impl(
```

### Steps to reproduce

-

### Logs

```shell
-
```

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Larpoux**
## Changes

Fixes #2178.
Fixes #2167.

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by Larpoux** [comment]
Please, is there someone to explain me why this check was unsuccessful ?

**Comment by fzyzcjy** [comment]
Click the "Details" button and we can see error logs. Looks like the codegen is not run. Thus try

```
cargo run --manifest-path /path/to/flutter_rust_bridge/frb_codegen/Cargo.toml -- generate
```

on `frb_example/integrate_third_party` folder

**Comment by Larpoux** [comment]
I would like to add a simple check that [#2178] is correctly fixed. How do you suggest doing that ?

**Comment by fzyzcjy** [comment]
Since that issue happens in realworld (web audio api), the simplest way may be: Just copy everything (e.g. flutter_rust_bridge.yaml, something.rs, ...) into frb_example/integrate_third_party, including the code that causes the problem (iirc it is `default_dart_async: false`). Then, since CI auto execute codegen tests etc on that example, we automatically ensure it works.

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Great job!

**Pull request merged**
