### PR TITLE
Provide more info for "Creating a Library" chapter, "CI/CD" section

### PR DESCRIPTION
**Pull request by DMouayad**
## Changes
Hey👋🏻
In the "Creating a Dart\Flutter Library" chapter of the book and regarding CI/CD:
- I've provided the location of  `pub-credentials.json` file on Windows and it'd be helpful if anyone can double-check.
- Add a lil bit of info on how to locally login to `Pub.dev`.

**And of course thanks to everyone for ur hard work.**

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (via `just precommit`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Briefly checked it and LGTM. cc @GregoryConrad who made that doc initially - do you have an interest to review it?

**Review by GregoryConrad — APPROVED** [review]
LGTM!

**Comment by DMouayad** [comment]
thank u all 4 your time 🤍.
@GregoryConrad appreciate the guide btw, I've created a Flutter/Dart package following it. You think it'd useful to reference it as an "example" in the book?
tho It's not ready yet, but I plan on finishing it in a couple of days.

**Comment by fzyzcjy** [comment]
@all-contributors please add @DMouayad for doc

**Pull request merged**
