### PR TITLE
Update flutter reqs to “>=3.0.0 <4.0.0”

### LINKED ISSUE #1201: Dart3 Feature flag
Just a Dart3 Feature Flag integration,

this is the python code that would have to be implemented, everything else works
```python
 with open('../lib/bridge_generated.dart', 'r+') as f:
        file = f.read()

        pattern_find = r'(:?final )?(class [a-zA-Z0-9_]+ extends (:?ffi\.Struct|ffi\.Opaque|ffi\.Union))'
        pattern_replace = r'final \2'

        file = re.sub(pattern_find, pattern_replace, file)

        #with open('../lib/bridge_generated_2.dart', 'w') as f:
        #    f.write(file)
        f.seek(0)
        f.write(file)
        f.truncate()
```

I think I would just add a -dart3 flagg?

### PR DESCRIPTION
**Pull request by Zaitam**
## Changes
Update the version used from ">=2.15.0 <3.0.0" to “>=3.0.0 <4.0.0”.
Close #1201

Todo:
- [ ] Allow usage of ffigen > 8.0.0

### CODE REVIEW

**Comment by Zaitam** [comment]
I am not in the current position to make further changes to the code for the upcoming hours. However, it seams like most errors must come from the update itself as the CI uses the SDK 2.19.2.
For the errors of `just rust_linter` and `just valgrind` I am not sure what could be causing it to trigger except the same as before.

**Comment by Zaitam** [comment]
I am now finishing some edits. I will like to highlight two new things:
- It requires ffigen > 8.0.0
- It requires dart > 3.0.0

I'll make an update now, but its hard to edit on mobile, and the just doesn't work for whatever reason, so I apologize for the delay and wish this time the CI becomes happy, as I have no cookies left for it.

**Comment by fzyzcjy** [comment]
Take your time!

**Comment by Zaitam** [comment]
I've been trying to fix the presented errors, but I am either not able to reproduce or not able to understand where the issue is located. The valgrind test has a leak, which I am not able to reproduce and on local test, it passes. The MacOS and iPad fail to load integration_test/main.dart, and I am not able to trace back the reason.
Last the iPhone returns:
```
Memory usage after maybe GC [NOTE: even if `externalUsage` increases, this is NOT a bug! It is because Flutter's ImageCache, which will cache about 100MB. See #19]: [MemoryUsage externalUsage: 2864, heapCapacity: 76029952, heapUsage: 68773056] dateLastServiceGC=1684147026290 now=1684147026722
```
Which I am also uncertain on what to do.
I apologize for my lack of knowledge on the area as to fix the issues. Would like to know if you had any insight which could help me solve it.

**Comment by fzyzcjy** [comment]
> Memory usage after maybe GC

I am not sure whether it is problem caused by this GC thing. Instead, I guess firstly we need to fix the following error. Can it be a real problem (e.g. Rust really do not give a correct image to Dart?)

```
2023-05-15T10:37:16.8326230Z ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
2023-05-15T10:37:16.8669240Z The following _Exception was thrown resolving an image frame:
2023-05-15T10:37:16.8791800Z Exception: Codec failed to produce an image, possibly due to invalid image data.
2023-05-15T10:37:16.8938100Z 
2023-05-15T10:37:16.9039340Z When the exception was thrown, this was the stack
2023-05-15T10:37:16.9141220Z ════════════════════════════════════════════════════════════════════════════════════════════════════
```

image

**Comment by fzyzcjy** [comment]
As for valgrind, i.e. the following error message, 

Firstly, maybe try to use the same version and execution environment as CI?

Secondly, a quick search reveals: https://github.com/gperftools/gperftools/blob/master/src/malloc_extension.cc , which seems to be the home of `tcmalloc`. In addition, a quick search shows Dart seems to use tcmalloc - e.g. https://github.com/dart-lang/sdk/pull/50998 (which tries to disable tcmalloc).

Then 

```
2023-05-15T10:25:03.4267161Z ==6179== HEAP SUMMARY:
2023-05-15T10:25:03.4267324Z ==6179==     in use at exit: 20,017 bytes in 205 blocks
2023-05-15T10:25:03.4267515Z ==6179==   total heap usage: 46,861 allocs, 46,656 frees, 8,393,465 bytes allocated
2023-05-15T10:25:03.4267600Z ==6179== 
2023-05-15T10:25:03.4507966Z ==6179== 8 bytes in 1 blocks are definitely lost in loss record 2 of 193
2023-05-15T10:25:03.4511930Z ==6179==    at 0x484A2F3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
2023-05-15T10:25:03.4513125Z ==6179==    by 0x3192AC: MallocExtension::Register(MallocExtension*) (in /home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/dart/main.exe)
2023-05-15T10:25:03.4515309Z ==6179==    by 0x314268: ??? (in /home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/dart/main.exe)
2023-05-15T10:25:03.4517983Z ==6179==    by 0x59025C: __libc_csu_init (in /home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/dart/main.exe)
2023-05-15T10:25:03.4519061Z ==6179==    by 0x4981E1B: __libc_start_main@@GLIBC_2.34 (libc-start.c:375)
2023-05-15T10:25:03.4521731Z ==6179==    by 0x2E37A9: (below main) (in /home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/dart/main.exe)
2023-05-15T10:25:03.4523780Z ==6179== 
2023-05-15T10:25:03.4529270Z ==6179== 608 bytes in 2 blocks are possibly lost in loss record 185 of 193
2023-05-15T10:25:03.4532027Z ==6179==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
2023-05-15T10:25:03.4534291Z ==6179==    by 0x40147D9: calloc (rtld-malloc.h:44)
2023-05-15T10:25:03.4535260Z ==6179==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
2023-05-15T10:25:03.4537508Z ==6179==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
2023-05-15T10:25:03.4540088Z ==6179==    by 0x49ED834: allocate_stack (allocatestack.c:430)
2023-05-15T10:25:03.4541021Z ==6179==    by 0x49ED834: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
2023-05-15T10:25:03.4543393Z ==6179==    by 0x5E43F00: std::sys::unix::thread::Thread::new (thread.rs:87)
2023-05-15T10:25:03.4546022Z ==6179==    by 0x5CB066A: std::thread::Builder::spawn_unchecked_ (mod.rs:592)
2023-05-15T10:25:03.4546990Z ==6179==    by 0x5CAFE54: std::thread::Builder::spawn_unchecked (mod.rs:486)
2023-05-15T10:25:03.4549194Z ==6179==    by 0x5CB0DD9: std::thread::Builder::spawn (mod.rs:418)
2023-05-15T10:25:03.4551951Z ==6179==    by 0x5CAF818: threadpool::spawn_in_pool (lib.rs:738)
2023-05-15T10:25:03.4552973Z ==6179==    by 0x5CAF2D7: threadpool::Builder::build (lib.rs:301)
2023-05-15T10:25:03.4555209Z ==6179==    by 0x5CAF53F: threadpool::ThreadPool::with_name (lib.rs:398)
2023-05-15T10:25:03.4557830Z ==6179==    by 0x5CA1E81: core::ops::function::FnOnce::call_once (thread.rs:42)
2023-05-15T10:25:03.4594416Z ==6179==    by 0x5CA6C7F: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
2023-05-15T10:25:03.4594512Z ==6179== 
2023-05-15T10:25:03.4594607Z ==6179== LEAK SUMMARY:
2023-05-15T10:25:03.4594738Z ==6179==    definitely lost: 8 bytes in 1 blocks
2023-05-15T10:25:03.4594883Z ==6179==    indirectly lost: 0 bytes in 0 blocks
2023-05-15T10:25:03.4595011Z ==6179==      possibly lost: 608 bytes in 2 blocks
2023-05-15T10:25:03.4595139Z ==6179==    still reachable: 19,401 bytes in 202 blocks
2023-05-15T10:25:03.4595245Z ==6179==         suppressed: 0 bytes in 0 blocks
2023-05-15T10:25:03.4595414Z ==6179== Reachable blocks (those to which a pointer was found) are not shown.
2023-05-15T10:25:03.4595823Z ==6179== To see them, rerun with: --leak-check=full --show-leak-kinds=all
2023-05-15T10:25:03.4595899Z ==6179== 
2023-05-15T10:25:03.4596104Z ==6179== For lists of detected and suppressed errors, rerun with: -s
2023-05-15T10:25:03.4596271Z ==6179== ERROR SUMMARY: 3388 errors from 119 contexts (suppressed: 0 from 0)
2023-05-15T10:25:03.4636069Z process code= 1
2023-05-15T10:25:03.4692499Z error: valgrind_util find this line is bad: ==6179==    definitely lost: 8 bytes in 1 blocks
2023-05-15T10:25:03.4758636Z error: Recipe `dart_test_valgrind` failed on line 80 with exit code 1
2023-05-15T10:25:03.4764941Z error: Recipe `ci_valgrind` failed on line 188 with exit code 1
2023-05-15T10:25:03.4781798Z ##[error]Process completed with exit code 1.
```

**Comment by Zaitam** [comment]
I just tried the valgrind_ci:
`Ubuntu 20.04.6 LTS x86_64`
`Dart SDK version: 3.0.1 (stable) (None) on "linux_x64"`
`valgrind-3.15.0`
And after running `$just ci_valgrind` (Small change on line 77 to $CARGO_TARGET_DIR="/workspaces/")
and got `valgrind_util thinks it is ok`
No other change done

**Comment by fzyzcjy** [comment]
If you don't mind, I will push to this branch to work on this PR, since frb needs to support 3.0 sooner or later.

**Comment by Zaitam** [comment]
All good!
I apologize for the lack of update on this PR. Haven't been able to update it both because lack of reproducibility and time.
Appreciate the work you've done to finish it and to develop the project!

**Pull request closed without merging**
