### PR TITLE
Added empty struct support

### PR DESCRIPTION
**Pull request by alexthe2**
*Please list issues fixed by this PR here, using format "Fixes #the-issue-number".*

## Checklist

- [x] An issue to be fixed by this PR is listed above. #835 
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (e.g. via `just refresh_all`).
- [x] ~~If this PR adds/changes features, documentations (in the `./book` folder) are updated.~~
- [ ] CI is passing.

## Remark for PR creator

* New contributors will be blocked by GitHub from running CI, but you can use [a trick](https://github.com/fzyzcjy/flutter_rust_bridge/pull/663#discussion_r962150638) to workaround this, and verify your code using CI by yourself.
* If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by alexthe2** [comment]
There seems to be a lot more formatting issues with the empty then initially expected

**Comment by fzyzcjy** [comment]
need to run local formatter, see `justfile`

**Comment by alexthe2** [comment]
> need to run local formatter, see `justfile`

I ran `just` and `just lint` is there anything else?

**Comment by fzyzcjy** [comment]
try ` just refresh_all`

**Comment by fzyzcjy** [comment]
as can be seen in checklist:

> The code generator is run and the code is formatted (e.g. via just refresh_all).

**Comment by fzyzcjy** [comment]
Maybe firstly fix it in another PR (just follow the linter warning - quite simple one line fix)

**Comment by fzyzcjy** [comment]
👀

**Comment by alexthe2** [comment]
Ohh I closed this one by accident when I force pushed, ups

**Comment by alexthe2** [comment]
Good news, I still have it 🙃 (apparently I had the bridge cloned in both ~, and ~/work with the latter having the code)

**Comment by alexthe2** [comment]
I'll resubmit this after datetime optional

**Comment by fzyzcjy** [comment]
Sure, take your time!

**Pull request closed without merging**
