### PR TITLE
Fix on `zero-copy` cargo feature

### PR DESCRIPTION
**Pull request by temeddix**
## Changes

[I made an additional PR](https://github.com/sunshine-protocol/allo-isolate/pull/41) at the `allo-isolate` repository. I accidentally left the outdated code in the last commit. I will update the version number of `allo-isolate` if the new PR is accepted.

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (via `just precommit`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Feel free to ping me when the upstream is released!

**Comment by temeddix** [comment]
https://github.com/sunshine-protocol/allo-isolate/commit/1c96082b9890d72dedf4f1a189acb3aab5e6c131
Now `allo-isolate` 0.1.17 is released and I updated the version number in `Cargo.toml`.

**Comment by temeddix** [comment]
@fzyzcjy

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Will merge after green CI :)

**Pull request merged**
