### PR TITLE
Refactor command module

### LINKED ISSUE #323: [Bug] Fix the broken CI
## problem 1: android

https://github.com/fzyzcjy/flutter_rust_bridge/runs/5137000331?check_suite_focus=true

```
[+31113 ms] > Configure project :integration_test
[        ] Warning: The plugin integration_test requires Android SDK version 31.
[   +1 ms] One or more plugins require a higher Android SDK version.
[   +2 ms] Fix this issue by adding the following to /Users/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/android/app/build.gradle:
[        ] android {
[        ]   compileSdkVersion 31
[        ]   ...
[        ] }

...

[ +101 ms] > Task :app:mergeDebugResources
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 15 actionable tasks: 14 executed, 1 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:checkDebugAarMetadata'.
[        ] > Multiple task action failures occurred:
[        ]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[        ]       > The minCompileSdk (31) specified in a
[        ]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[        ]         is greater than this module's compileSdkVersion (android-30).
[        ]         Dependency: androidx.window:window-java:1.0.0-beta04.
[        ]         AAR metadata file: /Users/runner/.gradle/caches/transforms-2/files-2.1/625039eaad011f884ddd84f857a44b7f/jetified-window-java-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
[        ]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[        ]       > The minCompileSdk (31) specified in a
[        ]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[        ]         is greater than this module's compileSdkVersion (android-30).
[        ]         Dependency: androidx.window:window:1.0.0-beta04.
[        ]         AAR metadata file: /Users/runner/.gradle/caches/transforms-2/files-2.1/a78fdf90e4c1f8464b19895cfb365f3f/jetified-window-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
```

later see:

```
           ┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────────┐
           │ [!] Your project requires a newer version of the Kotlin Gradle plugin.                           │
           │ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then     │
           │ update                                                                                           │
           │ /Users/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/android/buil │
           │ d.gradle:                                                                                        │
           │ ext.kotlin_version = '<latest-version>'                                                          │
           └──────────────────────────────────────────────────────────────────────────────────────────────────┘

```

## problem 2: windows

https://github.com/fzyzcjy/flutter_rust_bridge/runs/5137000113?check_suite_focus=true

```
[2022-02-10T07:07:26Z WARN  flutter_rust_bridge_codegen::commands] command="cmd" "/C" "rustfmt \"D:\\a\\flutter_rust_bridge\\flutter_rust_bridge\\frb_codegen\\..\\\\frb_example\\\\pure_dart\\\\rust\\\\src\\bridge_generated.rs\"" stdout= stderr=Error: file `"D:\a\flutter_rust_bridge\flutter_rust_bridge\frb_codegen\..\\frb_example\\pure_dart\\rust\\src\bridge_generated.rs"` does not exist
```

### PR DESCRIPTION
**Pull request by Desdaemon**
Partial fix #323

A few changes in the internal API:
- execute_command now takes a binary, a list of arguments and returns Output marked with `#[must_use]`
- Common failures are enumerated and handled, otherwise panic
- Changed llvm-path to take multiple parameters, and add some default search paths for LLVM

### CODE REVIEW

**Comment by SecondFlight** [comment]
Might be user error, but I'm seeing an issue with this. Running `flutter_rust_bridge_codegen` gives this error:
```
> .\scripts\bindgen.ps1
[2022-02-11T00:15:12Z DEBUG flutter_rust_bridge_codegen::commands] execute command: bin=dart args=["pub", "global", "list"] current_dir=None cmd="dart" "pub" "global" "list"
thread 'main' panicked at '"dart pub global list" failed: program not found', src\commands.rs:95:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Whereas just running `dart pub global list` gives this:
```
> dart pub global list
devtools 2.6.0
ffigen 4.1.2
```
I feel like I must be missing something since CI seems to have no issue, but I'm not sure what.

**Comment by Desdaemon** [comment]
@SecondFlight I'll check on my Windows machine too, I have only looked at CI results thus far.

**Comment by SecondFlight** [comment]
I suspect running it as `powershell -c dart pub global list` will fix the issue, at least on Windows. I saw a similar issue in another project, though I never figured out why the command couldn't be run directly so take that with a grain of salt.

**Comment by fzyzcjy** [comment]
> but dart works without issue. Maybe Flutter injects them on shell init?

Maybe it is because the user, when installing flutter, needs to modify his `~/.bashrc` (or `~/.zshrc` or sth like that)

**Comment by Desdaemon** [comment]
> This is coming from a build script, but I've also tried running it directly from both powershell and cmd, with the same result.

I haven't been able to reproduce this locally, but granted I just wiped my system so it is not much different from the CI's setup right now. I'm thinking this is an artifact of how Flutter used to inject `dart`, and now that 2.10 is out these edge cases are being taken care of. @SecondFlight Can you give me your `flutter doctor -v` output?

**Comment by SecondFlight** [comment]
Sure. I'm currently behind one version, but will be hopefully upgrading soon.

<details>
<summary>Click to expand</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.438], locale en-US)
    • Flutter version 2.8.1 at C:\Users\qbgee\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\qbgee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.438]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

! Doctor found issues in 2 categories.
```
</details>

**Comment by Desdaemon** [comment]
> It's been a while, but I remember running where dart and seeing no results, but dart works without issue. Maybe Flutter injects them on shell init?

I don't know if anyone finds this interesting, but on Powershell `where` is actually an alias to `Where-Object` and has nothing to do with `where.exe` on Windows, which explains the discrepancy.

**Comment by fzyzcjy** [comment]
CI passes! So should I merge it now?

**Comment by fzyzcjy** [comment]
🎉

**Pull request merged**
