### PR TITLE
Fix call build-web with fvm support

### PR DESCRIPTION
**Pull request by SirKrlos**
## Changes

Fix call ```flutter_rust_bridge_codegen build-web``` with fvm support.

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by SirKrlos** [comment]
Test performed in an environment with only the installed fvm, without the global version of the Flutter in the system.

Preview of error before the correction below:
$ flutter_rust_bridge_codegen build-web
sh: linha 1: dart: command not found
Error: Fail to execute command, please see logs above for details.

Preview of the result after correction:
$ flutter_rust_bridge_codegen build-web
Building package executable... 
Built flutter_rust_bridge:flutter_rust_bridge.
...

**Comment by fzyzcjy** [comment]
Looks great! 

Only one nit: CI seems failing because https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/12109542554/job/33758791441?pr=2429#step:9:4364, i.e. those two lines of logs pollute the output.
One potential way is to set `RUST_LOG=error` environment variable to mute it.

**Review by fzyzcjy — APPROVED** [review]

**Comment by SirKrlos** [comment]
After running ```flutter_rust_bridge_codegen build-web```, I noticed that an error is occurring when identifying the crate directory, even though I specified it in flutter_rust_bridge.yaml:

> which wasm-pack (pwd: null, env: null)
error: rust is not a crate directory.
Please specify the crate directory using "--crate <CRATE>".
Error: Fail to execute command, please see logs above for details.

It only works if I specify the rust crate path with the -c flag:
$ flutter_rust_bridge_codegen build-web -c rust_project_path
[INFO]: ✨ Done in 9.59s
[INFO]: 📦 Your wasm pkg is ready to publish at ...

I am investigating the cause of the problem.

**Comment by SirKrlos** [comment]
I identified that even in version 2.6.0 without the modifications of this MR to support fvm in build-web, the same error is also occurring.

$ flutter_rust_bridge_codegen build-web
sh: linha 1: dart: command not found
Error: Fail to execute command, please see logs above for details.

$ env PATH="$PATH:$HOME/fvm/versions/3.27.0-1.0.pre.669/bin" flutter_rust_bridge_codegen build-web
> which wasm-pack (pwd: null, env: null)
/home/user/.cargo/bin/wasm-pack
error: rust is not a crate directory.
Please specify the crate directory using "--crate <CRATE>".
Error: Fail to execute command, please see logs above for details.

Apparently it is not getting the crate directory from the flutter_rust_bridge.yaml file.

**Comment by fzyzcjy** [comment]
Hmm looks like currently it is reading from command line https://github.com/fzyzcjy/flutter_rust_bridge/blob/33d2d7ac22b6ff2055da861dd5a50eeb0b8a83f3/frb_dart/lib/src/cli/build_web/entrypoint.dart#L37

Feel free to PR to let it understand the configuration file!

**Comment by SirKrlos** [comment]
> Hmm quickly glanced at the code, looks like currently it may be reading from command line
> 
> https://github.com/fzyzcjy/flutter_rust_bridge/blob/33d2d7ac22b6ff2055da861dd5a50eeb0b8a83f3/frb_dart/lib/src/cli/build_web/entrypoint.dart#L37
> 
> (You can add some prints here and there to see what is going on)
> 
> Feel free to PR to let it understand the configuration file!

I noticed that the cli with the generate subcommand reads the flutter_rust_bridge.yaml file in:
https://github.com/fzyzcjy/flutter_rust_bridge/blob/33d2d7ac22b6ff2055da861dd5a50eeb0b8a83f3/frb_codegen/src/main.rs#L29

But the build-web subcommand does not:
https://github.com/fzyzcjy/flutter_rust_bridge/blob/33d2d7ac22b6ff2055da861dd5a50eeb0b8a83f3/frb_codegen/src/main.rs#L48

**Comment by fzyzcjy** [comment]
Totally agree! (I clicked the smile emoji days ago, but now I realize that will not trigger any notification to you, so I make a comment here). Now looks like we only need to fix that CI nit (with suggestions mentioned above) and we can merge it.

**Pull request merged**
