### PR TITLE
Fix sh permission

### LINKED ISSUE #1840: Problems with .sh script permissions
### Describe the bug

If the project is created under windows, then the sh script permissions cannot be changed to `0o755`, and when these under-privileged sh scripts are uploaded to github and executed when running `flutter build ios` in the MacOs Runner using Github Actions, the build process crashes due to the sh script permission issue and crashes.

(Ps. There seems to be a big problem with Flutter's logging system, when `flutter build ios` crashes due to sh permissions issues, Flutter incorrectly reports `Building a deployable iOS app requires a selected Development Team with a 
Please ensure that a Development Team is selected by.` )

### Steps to reproduce

1. In windows, use `flutter_rust_bridge_codegen create new_app` to create a new demo project.
2. Upload the project to github, then use github action to build a ios ipa.

The workflow file used above: https://github.com/canxin121/new_app/blob/main/.github/workflows/build.yml

#### with --verbose

```shell
2024-03-27T14:51:56.1985690Z /Users/runner/work/myapp/myapp/ios/Pods/../.symlinks/plugins/rust_lib_violet/ios/../cargokit/build_pod.sh: line 52: /Users/runner/work/myapp/myapp/rust_builder/cargokit/run_build_tool.sh: Permission denied
2024-03-27T14：51：56.1985690Z /Users/runner/work/myapp/myapp/ios/Pods/../.symlinks/plugins/rust_lib_violet/ios/../cargokit/build_pod.sh：第52行：/ Users/runner/work/myapp/myapp/rust_builder/cargokit/run_build_tool.sh：权限被拒绝
```

#### without --verbose:

```shell
Run flutter build ios --release --no-codesign
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.hw2 for device (ios-release)...
Updating minimum iOS deployment target to 12.0.
Upgrading Podfile
Running pod install...                                           1,183ms
Running Xcode build...                                          
Xcode build done.                                            4.9s
Failed to build iOS app
════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
Error: Process completed with exit code 1.
```

### Expected behavior

sh scripts should be secured with executable permissions before they are used.

### OS

Windows and MacOS

### PR DESCRIPTION
**Pull request by canxin121**
## Changes

close #1840 

Modify frb_codegen\assets\integration_template\rust_builder\macos\REPLACE_ME_RUST_CRATE_NAME.podspec and frb_codegen\assets\integration_ template\rust_builder\ios\REPLACE_ME_RUST_CRATE_NAME.podspec in the 
script_phases, add `Build Rust library` before the
` 
{
 :name => 'Change Permissions for Scripts', :script => 'chmod'
 :script => 'chmod a+x "$PODS_TARGET_SRCROOT/... /cargokit/run_build_tool.sh" && chmod a+x "$PODS_TARGET_SRCROOT/... /cargokit/build_pod.sh"', :execution_position = >:execution_position
 :execution_position => :before_compile
 },
'
to ensure that the sh script has executable permissions.

## Checklist

- [ √ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

### CODE REVIEW

**Comment by canxin121** [comment]
As verified by MacOS Runner using Github Actions, this pr works fine and resolves the previous permissions issue.
[Action](https://github.com/canxin121/new_app/actions/runs/8462195081/job/23183174297)

**Comment by fzyzcjy** [comment]
Good job! Curious whether it is possible to modify https://github.com/fzyzcjy/flutter_rust_bridge/blob/79b0746e792692f03d0b95ade60f29da6cd789a1/frb_codegen/src/library/integration/integrator.rs#L72 to make it work on windows? e.g. https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux

**Comment by canxin121** [comment]
> Good job! Curious whether it is possible to modify 好工作！好奇是否可以修改
> 
> https://github.com/fzyzcjy/flutter_rust_bridge/blob/79b0746e792692f03d0b95ade60f29da6cd789a1/frb_codegen/src/library/integration/integrator.rs#L72
> 
> to make it work on windows? e.g. https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux which discusses scenario when using git
> 让它在Windows上工作？例如https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux 讨论使用 git 时的场景

This shouldn't be possible as far as I know, the file permission systems of win and unix are very different, and even if you use Git Bash on win to `chmod a+x some.sh`, you'll find that git doesn't recognize that `some.sh` has changed.

Yet the sh permissions information can actually be uploaded to Github, which is why if you `flutter_rust_bridge_codegen.exe create new_app` on macOS and then go on to continue the process of reproducing the problem as mentioned in the issue, you'll find that the problem disappears.

**Comment by fzyzcjy** [comment]
I am considering the https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux

**Comment by canxin121** [comment]
> I am considering the
> 
> ```
> git update-index --chmod=+x myfile.sh
> ```
> 
> in the https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux

However, this does not automate the process of securing file permissions

**Comment by canxin121** [comment]
> I am considering the我正在考虑
> 
> ```
> git update-index --chmod=+x myfile.sh
> ```
> 
> in the https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux. Have you tried it on windows? (I am on mac so does not have a convenient environment to have a try)在 https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux 中。你在windows上试过吗？ （我用的是mac所以没有方便的环境来尝试）



> I am considering the我正在考虑
> 
> ```
> git update-index --chmod=+x myfile.sh
> ```
> 
> in the https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux. Have you tried it on windows? (I am on mac so does not have a convenient environment to have a try)在 https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux 中。你在windows上试过吗？ （我用的是mac所以没有方便的环境来尝试）

But if you want to use git to change the permissions on the sh file, this requires making sure that you have git version 2.9.0 or higher on this computer in order to do so, and I can't say for sure that this kind of use of git to change the permissions on the sh file retains the permissions information correctly when you don't use git (e.g., when you copy the file directly from Win to Unix)

**Comment by canxin121** [comment]
> I am considering the
> 
> ```
> git update-index --chmod=+x myfile.sh
> ```
> 
> in the https://superuser.com/questions/624368/how-to-chmod-x-a-file-in-windows-for-use-in-linux. Have you tried it on windows? (I am on mac so does not have a convenient environment to have a try)

But if you want to use git to change the permissions on the sh file, this requires making sure that you have git version 2.9.0 or higher on this computer in order to do so, and I can't say for sure that this kind of use of git to change the permissions on the sh file retains the permissions information correctly when you don't use git (e.g., when you copy the file directly from Win to Unix)

**Comment by fzyzcjy** [comment]
I see. Then what about we use `sh whatever_file.sh` instead of `whatever_file.sh`, since the former does not require `+x` permission while the latter requires, like:

```
// old: "$BASEDIR/run_build_tool.sh" build-pod "$@"
sh "$BASEDIR/run_build_tool.sh" build-pod "$@"
```

To do so, I guess we can PR for upstream (cargokit), and then modify this PR to bump the cargokit version.

(I am a bit worried about the chmod-when-build solution, since that will change the files *during a build*, and adding one extra stage looks a bit heavy)

**Comment by canxin121** [comment]
> I see. Then what about we use `sh whatever_file.sh` instead of `whatever_file.sh`, since the former does not require `+x` permission while the latter requires, like:
> 
> ```
> // old: "$BASEDIR/run_build_tool.sh" build-pod "$@"
> sh "$BASEDIR/run_build_tool.sh" build-pod "$@"
> ```
> 
> To do so, I guess we can PR for upstream (cargokit), and then modify this PR to bump the cargokit version.
> 
> (I am a bit worried about the chmod-when-build solution, since that will change the files _during a build_ when usually builds do not change things, and adding one extra stage looks a bit heavy)

It makes sense to do this if you want to change the upstream library, I added a step to change the permissions just because I didn't want to additionally change the upstream cargokit. 
I tend to change a much smaller range of code. Also I can't figure out if there's any problem left over from the chmod-when-build solution , since I think both podspec and sh file are things that codegen out at the same time and don't need to be changed for users who don't care about the build process.

**Comment by fzyzcjy** [comment]
> It makes sense to do this if you want to change the upstream library, I added a step to change the permissions just because I didn't want to additionally change the upstream cargokit.

No worries, it is common to change upstream dependencies, because by doing so, whoever using that library but not using flutter_rust_bridge will also enjoy the new feature/fix - which is good for the whole community.

> I tend to change a much smaller range of code. Also I can't figure out if there's any problem left over from the chmod-when-build solution , since I think both podspec and sh file are things that codegen out at the same time and don't need to be changed for users who don't care about the build process.

Totally agree, thus adding `sh` to upstream seems most minimal and avoids the possibility of chmod problem.

**Comment by canxin121** [comment]
> > It makes sense to do this if you want to change the upstream library, I added a step to change the permissions just because I didn't want to additionally change the upstream cargokit.如果您想更改上游库，那么这样做是有意义的，我添加了一个更改权限的步骤，只是因为我不想另外更改上游 Cargokit。
> 
> No worries, it is common to change upstream dependencies, because by doing so, whoever using that library but not using flutter_rust_bridge will also enjoy the new feature/fix - which is good for the whole community.不用担心，更改上游依赖项是很常见的，因为通过这样做，任何使用该库但不使用 flutter_rust_bridge 的人也将享受新功能/修复 - 这对整个社区都有好处。
> 
> > I tend to change a much smaller range of code. Also I can't figure out if there's any problem left over from the chmod-when-build solution , since I think both podspec and sh file are things that codegen out at the same time and don't need to be changed for users who don't care about the build process.我倾向于更改小范围的代码。另外，我无法弄清楚 chmod-when-build 解决方案是否遗留任何问题，因为我认为 podspec 和 sh 文件都是 codegen 同时生成的内容，并且不需要为以下用户进行更改不关心构建过程。
> 
> Totally agree, thus adding `sh` to upstream seems most minimal and avoids the possibility of chmod problem.完全同意，因此将 `sh` 添加到上游似乎是最小的，并且避免了 chmod 问题的可能性。



> > It makes sense to do this if you want to change the upstream library, I added a step to change the permissions just because I didn't want to additionally change the upstream cargokit.如果您想更改上游库，那么这样做是有意义的，我添加了一个更改权限的步骤，只是因为我不想另外更改上游 Cargokit。
> 
> No worries, it is common to change upstream dependencies, because by doing so, whoever using that library but not using flutter_rust_bridge will also enjoy the new feature/fix - which is good for the whole community.不用担心，更改上游依赖项是很常见的，因为通过这样做，任何使用该库但不使用 flutter_rust_bridge 的人也将享受新功能/修复 - 这对整个社区都有好处。
> 
> > I tend to change a much smaller range of code. Also I can't figure out if there's any problem left over from the chmod-when-build solution , since I think both podspec and sh file are things that codegen out at the same time and don't need to be changed for users who don't care about the build process.我倾向于更改小范围的代码。另外，我无法弄清楚 chmod-when-build 解决方案是否遗留任何问题，因为我认为 podspec 和 sh 文件都是 codegen 同时生成的内容，并且不需要为以下用户进行更改不关心构建过程。
> 
> Totally agree, thus adding `sh` to upstream seems most minimal and avoids the possibility of chmod problem.完全同意，因此将 `sh` 添加到上游似乎是最小的，并且避免了 chmod 问题的可能性。

Ok, I'll leave it up to you to figure it out since I'm really not familiar with the sh code and I don't have a mac to test it on.

**Comment by canxin121** [comment]
> > It makes sense to do this if you want to change the upstream library, I added a step to change the permissions just because I didn't want to additionally change the upstream cargokit.
> 
> No worries, it is common to change upstream dependencies, because by doing so, whoever using that library but not using flutter_rust_bridge will also enjoy the new feature/fix - which is good for the whole community.
> 
> > I tend to change a much smaller range of code. Also I can't figure out if there's any problem left over from the chmod-when-build solution , since I think both podspec and sh file are things that codegen out at the same time and don't need to be changed for users who don't care about the build process.
> 
> Totally agree, thus adding `sh` to upstream seems most minimal and avoids the possibility of chmod problem.

Ok, I'll leave the upstream changes to you, since I'm really not familiar with the sh code and I don't have a mac to test it on.

**Comment by fzyzcjy** [comment]
If you insist I will do that - but it is you who made the initial contribution, so I do not want to take your credit!

**Comment by canxin121** [comment]
> If you insist I will do that - but it is you who made the initial contribution, so I do not want to take your credit!

I'll try that then, I think I can use github action to test if it's working properly.

**Comment by canxin121** [comment]
Pr Tracking: https://github.com/irondash/cargokit/pull/65

A temporary normal working branch by switching the cargokit submodule to my cargokit branch: https://github.com/canxin121/flutter_rust_bridge/tree/test

**Comment by canxin121** [comment]
The upstream pr has been merged, and I updated the commit of the cargokit submodule.

**Comment by fzyzcjy** [comment]
LGTM! Maybe try

```
./frb_internal generate-run-frb-codegen-command-integrate --package frb_example/flutter_via_create
./frb_internal generate-run-frb-codegen-command-integrate --package frb_example/flutter_via_integrate
```

to update the corresponding files

**Comment by canxin121** [comment]
> LGTM! Maybe try LGTM！也许试试
> 
> ```
> ./frb_internal generate-run-frb-codegen-command-integrate --package frb_example/flutter_via_create
> ./frb_internal generate-run-frb-codegen-command-integrate --package frb_example/flutter_via_integrate
> ```
> 
> to update the corresponding files更新相应的文件

It failed to run.
```
PS D:\Git\flutter_rust_bridge> ./frb_internal generate-run-frb-codegen-command-integrate --package frb_example/flutter_via_create
Building package executable... 
Built flutter_rust_bridge_internal:flutter_rust_bridge_internal.
Pick temporary directory: D:\Git\flutter_rust_bridge\target\GenerateRunFrbCodegenCommandIntegrate\temp_2024-04-03T231148317263_744882832
Unhandled exception:
PathAccessException: Rename failed, path = 'D:\Git\flutter_rust_bridge\frb_example/flutter_via_create' (OS Error: 拒绝访问。
, errno = 5) (The meaning of the preceding sentence in Chinese is '(OS Error: Access Denied. , errno = 5)')
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195:7)
<asynchronous suspension>
#2      generateRunFrbCodegenCommandIntegrate.<anonymous closure> (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:334:7)
<asynchronous suspension>
#3      wrapMaybeSetExitIfChangedRaw (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:411:3)
<asynchronous suspension>
#4      _wrapMaybeSetExitIfChanged (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:400:3)
<asynchronous suspension>
#5      generateRunFrbCodegenCommandIntegrate (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:317:3)
<asynchronous suspension>
#6      SimpleConfigCommand.run (package:flutter_rust_bridge_internal/src/utils/makefile_dart_infra.dart:88:31)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      main (file:///D:/Git/flutter_rust_bridge/tools/frb_internal/bin/flutter_rust_bridge_internal.dart:30:3)
<asynchronous suspension>
```

**Comment by fzyzcjy** [comment]
Looks like permission error... Anyway, I will try to run it locally.

**Comment by canxin121** [comment]
> That's weird... Another way, if the local env somehow fails like that, is to copy-paste the diff e.g. https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/8539956598/job/23395926863?pr=1842 and apply it https://stackoverflow.com/questions/12320863/how-do-you-take-a-git-diff-file-and-apply-it-to-a-local-branch-that-is-a-copy-o.这很奇怪......另一种方法，如果本地环境以某种方式失败，就是复制粘贴差异，例如https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/8539956598/job/23395926863?pr=1842 并应用它 https://stackoverflow.com/questions/12320863/how-do-you-take-a- git-diff-file-and-apply-it-a-local-branch-that-is-a-copy-o。

I successfully executed the command with github action and downloaded all the files, then realized that none of the files had been modified, except for the difference between LF and CRLF

**Comment by fzyzcjy** [comment]
Well, I mean just save this to e.g. `a.patch`:

<details>

```
diff --git a/frb_example/flutter_via_create/rust_builder/cargokit/build_pod.sh b/frb_example/flutter_via_create/rust_builder/cargokit/build_pod.sh
index 379b9c6..ed0e0d9 100755
--- a/frb_example/flutter_via_create/rust_builder/cargokit/build_pod.sh
+++ b/frb_example/flutter_via_create/rust_builder/cargokit/build_pod.sh
@@ -49,7 +49,7 @@ do
   fi
 done
 
-"$BASEDIR/run_build_tool.sh" build-pod "$@"
+sh "$BASEDIR/run_build_tool.sh" build-pod "$@"
 
 # Make a symlink from built framework to phony file, which will be used as input to
 # build script. This should force rebuild (podspec currently doesn't support alwaysOutOfDate
diff --git a/frb_example/flutter_via_create/rust_builder/cargokit/build_tool/lib/src/android_environment.dart b/frb_example/flutter_via_create/rust_builder/cargokit/build_tool/lib/src/android_environment.dart
index 2b0b712..15fc9ee 100644
--- a/frb_example/flutter_via_create/rust_builder/cargokit/build_tool/lib/src/android_environment.dart
+++ b/frb_example/flutter_via_create/rust_builder/cargokit/build_tool/lib/src/android_environment.dart
@@ -118,7 +118,7 @@ class AndroidEnvironment {
 
     final cxxKey = 'CXX_${target.rust}';
     final cxxValue = path.join(toolchainPath, 'clang++$exe');
-    final cxxfFlagsKey = 'CXXFLAGS_${target.rust}';
+    final cxxFlagsKey = 'CXXFLAGS_${target.rust}';
     final cxxFlagsValue = targetArg;
 
     final linkerKey =
@@ -155,7 +155,7 @@ class AndroidEnvironment {
       ccKey: ccValue,
       cfFlagsKey: cFlagsValue,
       cxxKey: cxxValue,
-      cxxfFlagsKey: cxxFlagsValue,
+      cxxFlagsKey: cxxFlagsValue,
       ranlibKey: ranlibValue,
       rustFlagsKey: rustFlagsValue,
       linkerKey: selfPath,
diff --git a/frb_example/flutter_via_create/rust_builder/cargokit/cmake/cargokit.cmake b/frb_example/flutter_via_create/rust_builder/cargokit/cmake/cargokit.cmake
index 8832600..ddd05df 100644
--- a/frb_example/flutter_via_create/rust_builder/cargokit/cmake/cargokit.cmake
+++ b/frb_example/flutter_via_create/rust_builder/cargokit/cmake/cargokit.cmake
@@ -50,6 +50,7 @@ function(apply_cargokit target manifest_dir lib_name any_symbol_name)
     else()
         set(SCRIPT_EXTENSION ".sh")
         set(IMPORT_LIB_EXTENSION "")
+        execute_process(COMMAND chmod +x "${cargokit_cmake_root}/run_build_tool${SCRIPT_EXTENSION}")
     endif()
 
     # Using generators in custom command is only supported in CMake 3.20+
@@ -75,6 +76,7 @@ function(apply_cargokit target manifest_dir lib_name any_symbol_name)
         )
     endif()
 
+
     set_source_files_properties("${CMAKE_CURRENT_BINARY_DIR}/_phony_" PROPERTIES SYMBOLIC TRUE)
 
     if (TARGET ${target})
@@ -94,4 +96,4 @@ function(apply_cargokit target manifest_dir lib_name any_symbol_name)
     # Allow adding the output library to plugin bundled libraries
     set("${target}_cargokit_lib" ${OUTPUT_LIB} PARENT_SCOPE)
 
-endfunction()
\ No newline at end of file
+endfunction()
diff --git a/frb_example/flutter_via_create/rust_builder/cargokit/gradle/plugin.gradle b/frb_example/flutter_via_create/rust_builder/cargokit/gradle/plugin.gradle
index 28636e9..2fc1d70 100644
--- a/frb_example/flutter_via_create/rust_builder/cargokit/gradle/plugin.gradle
+++ b/frb_example/flutter_via_create/rust_builder/cargokit/gradle/plugin.gradle
@@ -58,7 +58,13 @@ abstract class CargoKitBuildTask extends DefaultTask {
         def manifestDir = Paths.get(project.buildscript.sourceFile.parent, project.cargokit.manifestDir)
 
         def rootProjectDir = project.rootProject.projectDir
-
+        
+        if (!Os.isFamily(Os.FAMILY_WINDOWS)) {
+            project.exec {
+                commandLine 'chmod', '+x', path
+            }
+        }
+        
         project.exec {
             executable path
             args "build-gradle"
diff --git a/frb_example/flutter_via_create/rust_builder/cargokit/run_build_tool.sh b/frb_example/flutter_via_create/rust_builder/cargokit/run_build_tool.sh
index 0e2c973..6e[594](https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/8539956598/job/23395926863?pr=1842#step:7:595)a2 100755
--- a/frb_example/flutter_via_create/rust_builder/cargokit/run_build_tool.sh
+++ b/frb_example/flutter_via_create/rust_builder/cargokit/run_build_tool.sh
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -e
 
@@ -42,6 +42,12 @@ void main(List<String> args) {
 }
 EOF
 
+# Create alias for `shasum` if it does not exist and `sha1sum` exists
+if ! [ -x "$(command -v shasum)" ] && [ -x "$(command -v sha1sum)" ]; then
+  shopt -s expand_aliases
+  alias shasum="sha1sum"
+fi
+
 # Dart run will not cache any package that has a path dependency, which
 # is the case for our build_tool_runner. So instead we precompile the package
 # ourselves.
diff --git a/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec b/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec
index 30f5eb2..8a78[601](https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/8539956598/job/23395926863?pr=1842#step:7:602) 100644
--- a/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec
+++ b/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec
@@ -42,4 +42,4 @@ A new Flutter FFI plugin project.
     'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386',
     'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib_flutter_via_create.a',
   }
-end
+end
\ No newline at end of file
diff --git a/frb_example/flutter_via_create/rust_builder/macos/rust_lib_flutter_via_create.podspec b/frb_example/flutter_via_create/rust_builder/macos/rust_lib_flutter_via_create.podspec
index d2bbc3b..9403cf8 100644
--- a/frb_example/flutter_via_create/rust_builder/macos/rust_lib_flutter_via_create.podspec
+++ b/frb_example/flutter_via_create/rust_builder/macos/rust_lib_flutter_via_create.podspec
@@ -41,4 +41,4 @@ A new Flutter FFI plugin project.
     'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386',
     'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib_flutter_via_create.a',
   }
-end
+end
```

</details>

and git apply that patch.

Anyway, I may just run it later when merging this PR.

**Comment by fzyzcjy** [comment]
@all-contributors please add @canxin121 for code

**Pull request merged**
