### PR TITLE
Switch from `dart-sys-fork` to `dart-sys`

### LINKED ISSUE #2434: Switch from `dart-sys-fork` to `dart-sys` crate
Are there any blockers to switching to the `dart-sys` crate from crates.io instead of using `dart-sys-fork`? From what I can tell, the changes in `dart-sys-fork` have already [been merged][1] upstream. Would it make sense to use the `dart-sys` crate directly instead?

[1]: https://github.com/dart-sys/dart-sys/commit/3d8ebd6fddbbade907dc5e0c54bf1a3f8328a55e

### PR DESCRIPTION
**Pull request by evdokimovs**
## Changes

Fixes #2434.

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Looks like the next subpart needs update as well... Anyway just try `./frb_internal generate-internal` for a bunch of internal things.

**Comment by fzyzcjy** [comment]
Well... Looks like we need to change other things to match the update. If you would like to do it feel free to do so! Alternatively, just revert the generate-internal-blahblah code and merge it first, and I will fix those updates.

**Comment by evdokimovs** [comment]
@fzyzcjy ,

> Well... Looks like we need to change other things to match the update. If you would like to do it feel free to do so! Alternatively, just revert the generate-internal-blahblah code and merge it first, and I will fix those updates.

I fixed that problem, so we can merge, I think.

**Comment by fzyzcjy** [comment]
Great job!

**Comment by fzyzcjy** [comment]
@all-contributors please add @evdokimovs for code

**Comment by fzyzcjy** [comment]
Probably within a day :)

**Comment by fzyzcjy** [comment]
Now!

**Comment by fzyzcjy** [comment]
You are welcome!

**Pull request merged**
