### PR TITLE
Add support for unit return type.

### LINKED ISSUE #197: Is Result<()> as return type unsupported?
**Describe the bug**
I am getting the following error when running flutter_rust_bridge_codegen on a file that uses `Result<()>` as return type for a function.

```
thread 'main' panicked at 'unsupported type_string: Result<()>'
```

Is it indeed a limitation on the Dart side that a function cannot return no value?

### PR DESCRIPTION
**Pull request by surban**
This is my first try of adding support for the unit return type.
I don't have much experience with Dart so please treat with care.

Fixes #197.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Thanks for your contribution! Could you please add a very simple test on https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/ : 

1. Add a function that returns unit in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs. Just a few lines are enough.
2. Run code generator in this pure_dart example.
3. Add a few lines in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/dart/lib/main.dart to make simple assertions. You may do simple things like `await api.handleReturnUnit();` without any assertions since "void" is not something you can assert.

Totally <10 line of code is needed ;)

**Comment by fzyzcjy** [comment]
@all-contributors bot please add @surban for code

**Comment by fzyzcjy** [comment]
👀

**Comment by surban** [comment]
Sure, will do. Just busy today with other stuff.

**Comment by surban** [comment]
Hi.

I've added the tests.

**Comment by surban** [comment]
Sure, I've rebased on master.

**Comment by fzyzcjy** [comment]
some ci failed. could you plz check: https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CONTRIBUTING.md

**Comment by surban** [comment]
Could you rerun CI?

**Comment by fzyzcjy** [comment]
sure

**Comment by fzyzcjy** [comment]
e

**Comment by fzyzcjy** [comment]
🎉

**Pull request merged**
