### PR TITLE
fix(codegen): generate decl of `store_dart_post_cobject` when full_dep enabled

### LINKED ISSUE #1772: The bridge always wants to load a framework on iOS
### Describe the bug

I'm trying to upgrade a frbv1 project to frbv2. The upgrade is successful on Android, but not iOS. With frbv1, the native lib is built as staticlib with a project generated by cargo-xcode. However, after upgrading to frbv2, the dart side always wants to load `native.framework/native`. I looked through the examples in this repo, but they all use cargokit. Is there a smooth upgrade path to still use the static lib without framework, or a way to change the xcode project to generate a dummy framework?

### Steps to reproduce

The instructions here is interesting. Does `dart_minimal` really run well on iOS?

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'native.framework/native': dlopen(native.framework/native, 0x0001): tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootnative.framework/native' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/native.framework/native' (errno=2), '/usr/lib/swift/native.framework/native' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/native.framework/native' (errno=2), '/usr/lib/swift/native.framework/native' (errno=2, not in dyld cache), '/Users/berrysoft/Library/Developer<…>
```

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Berrysoft**
## Changes

Fixes #1772 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [x] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! I will re-run the CI since it seems to be merely flaky.

**Comment by Berrysoft** [comment]
The two failed checks seemed not finding chrome.

**Comment by fzyzcjy** [comment]
I agree, maybe the underlying github ci is upgrading etc. Will check a bit later when having time.

**Comment by fzyzcjy** [comment]
@all-contributors please add @Berrysoft for code

**Pull request merged**
