### PR TITLE
documents customizing the rust folder location

### PR DESCRIPTION
**Pull request by patmuk**
## Changes
Documents customizing the rust project folder as done in #1459.

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [x] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator
@fzyzcjy have a look and merge it at your convince.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! I may want to make this PR open until the next batch, at that time I will deal with a few things related to doc at the same time.

**Comment by fzyzcjy** [comment]
(I will merge it and then move the doc)

**Comment by fzyzcjy** [comment]
Oops, I realize a small problem (after merging it): This would be greater if we can make it automatic. 

Sketch: The code is in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_codegen/src/library/integration/integrator.rs (quite short indeed). 

We may just mimic https://github.com/fzyzcjy/flutter_rust_bridge/blob/7e70c19ef123114355b4da9a2ac3b78e73ba070c/frb_codegen/src/library/integration/integrator.rs#L124, and add a `.replace("REPLACE_ME_RUST_DIR_NAME", ...)`. At the same time, change the template like https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_codegen/assets/integration_template/rust_builder/ios/rust_builder.podspec, from hardcoding paths, into using that String placeholder.

I will temporarily revert this PR on master before finishing this discussion :)

**Comment by patmuk** [comment]
I totally agree! I made a PR #1561. I will today (time-boxed) see how far I can come. Would need to pick it up later, as I will be busy these days :(. Though feel free to work on the PR as well :)

**Comment by fzyzcjy** [comment]
Sure, take your time and looking forward to it!

**Pull request merged**
