### PR TITLE
Implement `impl ... for ...`

### LINKED ISSUE #1894: `impl ... for ...` doesn't generate code
### Describe the bug

Implementing a public trait (tested with `Default`) for a rust struct doesn't generate corresponding dart code.

### Steps to reproduce

1. In the default template change the simple file to: 
```rust
pub struct A {
    val: u32
}

impl Default for A {
    fn default() -> Self {
        A {
            val: 0
        }
    }
}

impl A {
    pub fn new() -> Self {
        A {
            val: 0
        }
    }
}
```

2. run `flutter_rust_bridge_codegen generate && flutter pub get`
3. The generated dart class (file `simple.dart`) contains the static `A.new_instance` method but no `default` method. The new method works as expected

### Logs

```shell
https://pastebin.com/irT3KWT0 (github said issue is too long)
```

### Expected behavior

I expect the generator to either:
- Create a static `default` method in the `A` dart class (prefered)
- Create a default function
- Create some other class/mixin with a default function

### Generated binding code

_No response_

### OS

Arch Linux

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

```shell
~/Coding/Flutter/derdilla-desktop/apps/calculator git:[main]
flutter doctor -v
[✓] Flutter (Channel beta, 3.22.0-0.2.pre, on Garuda Linux 6.8.7-AMD-znver3, locale en_US.UTF-8)
    • Flutter version 3.22.0-0.2.pre on channel beta at /home/derdilla/bin/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 312b9e81e9 (2 days ago), 2024-04-18 20:57:54 -0700
    • Engine revision a86e74cf06
    • Dart version 3.4.0 (build 3.4.0-282.2.beta)
    • DevTools version 2.34.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/derdilla/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.2
    • ninja version 1.11.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/bin/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /home/derdilla/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 79.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Garuda Linux 6.8.7-AMD-znver3

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Version of `clang++`

17.0.6 (clang --version)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NobodyForNothing**
## Changes

Generates methods when implementing traits for structs.

Fixes #1894 

Also Fixes a typo on the website.

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [X] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

Running `./frb_internal precommit --mode slow` locally always results in compilation errors/panics and changes a bunch of tracked files, even on the master branch. It would be great if someone could help me resolve this. 

I'm also unsure how to use twin tests and left that part out.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
> Running ./frb_internal precommit --mode slow locally always results in compilation errors/panics and changes a bunch of tracked files, even on the master branch. It would be great if someone could help me resolve this.
I'm also unsure how to use twin tests and left that part out.

Then maybe `./frb_internal generate-internal-frb-example-pure-dart ; ./frb_internal precommit-generate`

**Comment by fzyzcjy** [comment]
This is needed when implementing auto scanning of external types, thus I will continue on it.

**Comment by fzyzcjy** [comment]
@all-contributors please add @NobodyForNothing for code,doc

**Comment by NobodyForNothing** [comment]
@fzyzcjy thank you for continuing this, I got a bit overwhelmed with the codebase and kinda forgot about this tbh. 

A fair warning: Be careful when using this code. At this stage this was primarily me trying to understand the necessary changes and by no means a production ready implementation.

**Comment by fzyzcjy** [comment]
No worries, I made some necessary changes, and there are CI and thousands of tests to protect us as well!

**Pull request merged**
