### PR TITLE
docs: add Dart/Flutter library setup documentation

### LINKED ISSUE #845: Explain how to create a Flutter package with Rust (instead of an app)
Currently we have a lot of doc if we want to create a flutter app with rust. but no doc or template yet for flutter packages.

related: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/819#discussioncomment-4143007

### PR DESCRIPTION
**Pull request by GregoryConrad**
Fixes #845

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job, looking forward to it!

**Comment by GregoryConrad** [comment]
Hi, this PR is getting pretty close to done (just have a few pages left to write), so if you want to take a quick first look at the PR (since it is getting pretty massive), thoughts/recommendations would be welcome!

Here's what I have left to write before I would consider this PR done:
- [ ] `dart_only.md`
- [ ] `flutter_wrapper.md`
- [ ] `melos.md`

**Comment by GregoryConrad** [comment]
In the future, it'd probably be a good idea for someone to make a mason brick to simplify the process of creating a library with FRB. A lot of the setup instructions documented here are boilerplate, but some also talk about how/why things work the way they do.

**Comment by GregoryConrad** [comment]
@fzyzcjy Ready for review!

**Comment by fzyzcjy** [comment]
> In the future, it'd probably be a good idea for someone to make a mason brick to simplify the process of creating a library with FRB. A lot of the setup instructions documented here are boilerplate, but some also talk about how/why things work the way they do.

IIRC @Desdaemon has made a brick for the non-library case btw

> @fzyzcjy Ready for review!

Reviewing!

**Review by fzyzcjy — APPROVED** [review]
Great job - this documentation is quite elaborated! Only a few nits and ready to merge :)

**Comment by fzyzcjy** [comment]
@all-contributors please add @GregoryConrad  for doc

**Comment by fzyzcjy** [comment]
@all-contributors please add @GregoryConrad for code

(given that there are quite a bit of scripts in the doc - IMHO they should be categorized as code)

**Pull request merged**
