### PR TITLE
Partially fix issue with thiserror error

### LINKED ISSUE #1548: [Bug] Rust says `?` couldn't convert the error to `CoSaveError`
### Describe the bug

I'm getting an error when exporting  a function with signature -  
```rust
pub fn get_users(&self) -> Result<Vec<User>, CoSaveError> {}
```
Error:
```
`?` couldn't convert the error to `CoSaveError`
the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
the following other types implement trait `FromResidual<R>`:
  <Result<T, F> as FromResidual<Yeet<E>>>
  <Result<T, F> as FromResidual<Result<Infallible, E>>>
required for `Result<Vec<User>, CoSaveError>` to implement `FromResidual<Result<Infallible, anyhow::Error>>`
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
https://pastebin.com/cz75pv5p
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

```shell
fn wire_StorageService_get_users_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<flutter_rust_bridge::RustOpaque<std::sync::RwLock<StorageService>>>
        + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "StorageService_get_users",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco((move || {
                    let api_that = api_that.rust_auto_opaque_decode_ref()?;
                    crate::api::storage_service::StorageService::get_users(&api_that)
                })())
            }
        },
    )
}
```

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akashgurava**
## Changes

Fixes (partially) #1548 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
(I guess `./frb_internal precommit --mode slow` is needed to ensure latest code are generated)

**Comment by akashgurava** [comment]
When I run that, its removing ffigen from pubspec.yaml for examples and build fails complaining ffigen is missing.
image

**Comment by akashgurava** [comment]
Also this works fine with the same error.
```rust
pub fn new(app_doc_dir: String) -> Result<StorageService, CoSaveError> {..}
```
Generated function:
```rust
fn wire_StorageService_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    app_doc_dir: impl CstDecode<String> + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "StorageService_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_app_doc_dir = app_doc_dir.cst_decode();
            move |context| {
                transform_result_dco((move || -> Result<_, anyhow::Error> {
                    Result::<_, anyhow::Error>::Ok(
                        flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
                            crate::api::storage_service::StorageService::new(api_app_doc_dir)?,
                        ),
                    )
                })())
            }
        },
    )
}
```

**Comment by fzyzcjy** [comment]
> When I run that, its removing ffigen from pubspec.yaml for examples and build fails complaining ffigen is missing.

I guess it is because the script fails when executing. Anyway, use `./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart` firstly and ensure the related tests pass; the other things are trivial.

**Comment by fzyzcjy** [comment]
> Also this works fine with the same error.

This seems to be because anyhow::Error is used here, while we know it should be CoSaveError.
The code is in the file https://github.com/fzyzcjy/flutter_rust_bridge/blob/1c2fb7fd32935e90fa1d2941eb1c5c5af04f8f15/frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs

**Comment by fzyzcjy** [comment]
@all-contributors please add @akashgurava for code

**Comment by fzyzcjy** [comment]
I will work on it

**Pull request merged**
