### PR TITLE
Improves the documentation on how to configure build.rs

### LINKED ISSUE #1742: Improve `build.rs` configuration documentations
### Describe the bug

When trying to implement a build.rs, so changes in the rust code trigger code generation, I stumbled over the following issues:

1. The example [build.rs](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/build.rs) in [the documentation](https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/build-rs) does not exist.

Another build.rs can be found [here](https://github.com/fzyzcjy/flutter_rust_bridge/blob/ed07500584cba06754c3dfab210fb850b014b83f/frb_example/dart_build_rs/rust/build.rs#L4), its [cargo.toml](https://github.com/fzyzcjy/flutter_rust_bridge/blob/ed07500584cba06754c3dfab210fb850b014b83f/frb_example/dart_build_rs/rust/Cargo.toml) points to the local frb repository (as CI should take the latest unpublished code).
However, it is not documented what needs to be imported when using the published code.

### Steps to reproduce

Works, if the missing peaces are figured ;)

### Logs

```shell
not applicable
```

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

I will create a small PR describing the setup better and fixing the link :)

### PR DESCRIPTION
**Pull request by patmuk**
## Changes

Fixes #1742 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

@fzyzcjy please not that I took the liberty to change the md-file to have one sentence per line. In this way, future changes are easier to see in the diff. The output should not be affected by this reformatting.

Probably my description is a bit to verbose - feel free to reformulate or ask me to do so!

### CODE REVIEW

**Comment by patmuk** [comment]
@fzyzcjy I guess all is fine (except for you to have an editorial look upon the proposed reformulation).
The CI fails two tasks:
1. Code coverage shrank -> not sure why, as even the [report](https://app.codecov.io/gh/fzyzcjy/flutter_rust_bridge/pull/1743) states that no file changed. I accidentally used a wrong comment sign in the cargo.toml, and fixed that - so maybe it complains about introducing and then removing a line. Though the report compares master with the last commit in this branch.
2. [frb_example/flutter_via_create](https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/7828079015/job/21357267498?pr=1743) fails. I did not changed anything there, maybe a flaky run?

**Comment by fzyzcjy** [comment]
> Code coverage shrank, frb_example/flutter_via_create fails

Just flaky, no worries!

**Comment by patmuk** [comment]
@fzyzcjy thanks for the corrections!

**Comment by fzyzcjy** [comment]
You are welcome!

**Pull request merged**
