### PR TITLE
example: check bool in enum conversion

### PR DESCRIPTION
**Pull request by TENX-S**

### CODE REVIEW

**Comment by fzyzcjy** [comment]
"valgrind test" runs happily, so no compile error imho

**Comment by SecondFlight** [comment]
Hey @TENX-S, make sure you're adding `--dart-format-line-length 120` when you run codegen in the example projects.

If you're on Windows, here's a couple extra steps you'll need as well: https://github.com/fzyzcjy/flutter_rust_bridge/pull/536#issuecomment-1170259918

**Comment by TENX-S** [comment]
Sorry for the late reply. I'll try to reproduce https://github.com/fzyzcjy/flutter_rust_bridge/issues/549 in the next few days.

**Comment by fzyzcjy** [comment]
Take your time :)

**Comment by TENX-S** [comment]
The code lint does complain about the invalid assignment:

Screen Shot 2022-07-07 at 10 00 08

Screen Shot 2022-07-07 at 10 00 35

**Comment by fzyzcjy** [comment]
Maybe need to modify a bit until CI fails :)

**Comment by TENX-S** [comment]
Is CI silence because of a merge conflict?

**Comment by fzyzcjy** [comment]
> Is CI silence because of a merge conflict?

I guess so

**Comment by fzyzcjy** [comment]
Just merge and *throw away* those bridge_generated thing, and run code generator again.

**Comment by TENX-S** [comment]
I reset the HEAD to the fork point and commit from that point and push. Why is there still a merge conflict

**Comment by TENX-S** [comment]
Can I close this PR and reopen a new one?

**Comment by fzyzcjy** [comment]
> 
Can I close this PR and reopen a new one?

Sure

**Pull request closed without merging**
