### PR TITLE
Implement `Option<T>`

### PR DESCRIPTION
**Pull request by Desdaemon**
Rough implementation of `Option<T>` to Dart's `T?`.
I based this on the implementation of `Box<T>` where a null is equivalent to passing a nullptr down the wire.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by fzyzcjy** [comment]
By the way, could you please add a line to CHANGELOG.md (only the one in the repo root)? I find I cannot do that on the PR.

**Comment by Desdaemon** [comment]
@fzyzcjy I would like some advice on boxing primitives. I was thinking that this could go in two ways:
- We don't implement Options for primitives, and all wire API calls will only involve plain primitives.
- We allow Options of primitives, under the assumption that all Dart callers have to allocate memory for the primitive.
This could give some freedom in type design, but personally I don't have a use case for this. 

Perhaps this behavior could be defined by the user, which I think is the best compromise for now.

**Comment by fzyzcjy** [comment]
> I was completely unaware of this solution, thank you for bringing it up! I think this will help out a lot.

You are welcome!

> Basically I was thinking that because the wire type is a pointer, it has to point to some underlying memory
and that being the case makes boxing primitives from Rust's side easier to deal with.

IMHO maybe no. For example, if wire type is `int32_t* value`, it can be null pointer, so it does not point to anywhere.

**Comment by fzyzcjy** [comment]
> btw ignore the master's code update for a while (and do not merge into this pr). I am developing a new feature and will push some commits later.

features added. you may merge upstream now (or later, of course both ok)

**Comment by fzyzcjy** [comment]
let me have a review

**Comment by fzyzcjy** [comment]
Really great job! Only some code review above asking minor questions.

**Comment by fzyzcjy** [comment]
@all-contributors please add @Desdaemon for code, test

**Comment by fzyzcjy** [comment]
Great job! Let me have a review

**Pull request merged**
