### PR TITLE
Automatically generate getters and setters for public fields of opaque types

### PR DESCRIPTION
**Pull request by fzyzcjy**
## Changes

_Please list issues fixed by this PR here, using format "Fixes #the-issue-number"._

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by cabaucom376** [comment]
On dev 35 I just used a macro to loop through my properties and define getters for my classes. I love the getters/setters are now automatically generated by frb. Quick question while following the [properties documentation](https://cjycode.com/flutter_rust_bridge/guides/functions/properties) to overwrite the default getter/setter for a custom object. Is there a way to disable only setter generation for the struct? Or better yet what would be causing this error as I am seemingly following the same structure as the documentation?
image

**Comment by cabaucom376** [comment]
Update: I figured out to remove the pub from the id in the struct and manually define the getters/setters but the generation on the getter side is returning void for some reason:

```rs
use surrealdb::sql::{Thing, thing};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[frb(opaque)]
pub struct ShardModel {
    id: Thing,
    pub sequence: u16,
    pub name: String,
    pub description: Option<String>,
    pub collections: Option<Vec<CollectionModel>>,
    pub notes: Option<Vec<NoteModel>>,
    pub tasks: Option<Vec<TaskModel>>,
}
impl ShardModel {
    #[frb(sync, getter)]
    pub fn id (&self) -> String {
        self.id.to_raw()
    }
    #[frb(sync, setter)] // Still has: "duplicate definitions with name `id` duplicate definitions for `id`" error.
    pub fn id (&mut self, id: &str) {
        self.id = thing(id);
    }
}
```

```dart
// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ShardModel>>
@sealed
class ShardModel extends RustOpaque {
  ShardModel.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  ShardModel.sseDecode(BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ShardModel,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ShardModel,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ShardModelPtr,
  );

  List<CollectionModel>? get collections =>
      RustLib.instance.api.crateDatabaseModelsShardModelGetCollections(
        that: this,
      );

  String? get description =>
      RustLib.instance.api.crateDatabaseModelsShardModelGetDescription(
        that: this,
      );

  String get name => RustLib.instance.api.crateDatabaseModelsShardModelGetName(
        that: this,
      );

  List<NoteModel>? get notes =>
      RustLib.instance.api.crateDatabaseModelsShardModelGetNotes(
        that: this,
      );

  int get sequence =>
      RustLib.instance.api.crateDatabaseModelsShardModelGetSequence(
        that: this,
      );

  List<TaskModel>? get tasks =>
      RustLib.instance.api.crateDatabaseModelsShardModelGetTasks(
        that: this,
      );

  String get id => RustLib.instance.api.crateDatabaseModelsShardModelId(
        that: this,
      ); // Notice its not a "Get" method

  void set id(String id) =>
      RustLib.instance.api.crateDatabaseModelsShardModelId(that: this, id: id); // Not a "Set" method

  void set collections(List<CollectionModel>? collections) =>
      RustLib.instance.api.crateDatabaseModelsShardModelSetCollections(
          that: this, collections: collections);

  void set description(String? description) =>
      RustLib.instance.api.crateDatabaseModelsShardModelSetDescription(
          that: this, description: description);

  void set name(String name) => RustLib.instance.api
      .crateDatabaseModelsShardModelSetName(that: this, name: name);

  void set notes(List<NoteModel>? notes) => RustLib.instance.api
      .crateDatabaseModelsShardModelSetNotes(that: this, notes: notes);

  void set sequence(int sequence) => RustLib.instance.api
      .crateDatabaseModelsShardModelSetSequence(that: this, sequence: sequence);

  void set tasks(List<TaskModel>? tasks) => RustLib.instance.api
      .crateDatabaseModelsShardModelSetTasks(that: this, tasks: tasks);
}
```

crateDatabaseModelsShardModelId:
```dart
  void crateDatabaseModelsTaskModelId(
      {required TaskModel that, required String id, dynamic hint});
```

**Comment by fzyzcjy** [comment]
Hi, what about using `#[frb(sync, setter, name="id")] fn set_id() {}`

**Comment by fzyzcjy** [comment]
Could you please create a new issue? Then we can discuss it further. For example, one way is to enhance it to auto recognize and remove `get_` or `set_` prefix.

**Pull request merged**
