### PR TITLE
Support naive date

### PR DESCRIPTION
**Pull request by TrackerSB**
## Changes

Implement the feature requested in https://github.com/fzyzcjy/flutter_rust_bridge/issues/1833.

(EDIT by @fzyzcjy to let github link automatically) Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/1833

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by TrackerSB** [comment]
Replaces #1834

**Comment by TrackerSB** [comment]
Does "./frb_internal precommit --mode slow" enforce having installed all required targets like wasm32, windows, macos, android, etc.?

**Comment by TrackerSB** [comment]
I'm asking asking since it deletes all folders related to windows, ios, macos and android in flutter_via_create and flutter_via_integrate without obviously failing.
[output.log](https://github.com/fzyzcjy/flutter_rust_bridge/files/15442958/output.log)

**Comment by fzyzcjy** [comment]
Given the CI errors, I guess you mainly need `./frb_internal generate-internal-frb-example-pure-dart ; ./frb_internal precommit-generate`, which is faster (and runs a subset of full precommit).

**Comment by TrackerSB** [comment]
Almost there, but I have to have a look into the asynchronous variant of the tests.

**Comment by fzyzcjy** [comment]
Looking forward to it!

**Comment by TrackerSB** [comment]
How can it be that only Ubuntu and windows are falling or do I misinterpret the CI output?

**Comment by fzyzcjy** [comment]
> How can it be that only Ubuntu and windows are falling or do I misinterpret the CI output?

Maybe MacOS is still in queue?
Usually I only look at Ubuntu if multiple platform fails, since that one often runs fastest.

**Comment by TrackerSB** [comment]
```
[2024-06-23T08:11:52.519Z INFO frb_codegen/src/library/codegen/parser/mir/parser/ty/enum_or_struct.rs:73] Skip parsing enum_or_struct `NamespacedName { namespace: Namespace { joined_path: "crate::api::pseudo_manual::rust_opaque_sync_twin_moi" }, name: "FrbOpaqueSyncReturnTwinMoi" }` because of error (e=struct with unit fields are not supported yet, what about using `struct FrbOpaqueSyncReturnTwinMoi {}` or `#[frb(opaque)] struct FrbOpaqueSyncReturnTwinMoi;` instead
```
```
Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/stefan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/error.rs:83:36
   1: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::structure::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_struct
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/structure.rs:47:29
   2: <lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::structure::EnumOrStructParserStruct as lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::enum_or_struct::EnumOrStructParser<lib_flutter_rust_bridge_codegen::library::codegen::ir::mir::ty::structure::MirStructIdent,lib_flutter_rust_bridge_codegen::library::codegen::ir::mir::ty::structure::MirStruct,syn::item::ItemStruct>>::parse_inner_impl
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/structure.rs:119:9
   3: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::enum_or_struct::EnumOrStructParser::parse_impl
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/enum_or_struct.rs:69:37
   4: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::enum_or_struct::EnumOrStructParser::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/enum_or_struct.rs:31:22
   5: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::structure::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_type_path_data_struct
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/structure.rs:29:9
   6: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::path::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_type_path_core
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/path.rs:47:32
   7: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::path::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_type_path
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/path.rs:12:47
   8: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::ty::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_type_inner
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/ty.rs:34:30
   9: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::ty::<impl lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParserWithContext>::parse_type
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/ty.rs:11:19
  10: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::ty::TypeParser::parse_type
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/ty/mod.rs:124:9
  11: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::function::auto_accessor::parse_auto_accessors_of_struct
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/mod.rs:79:15
  12: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::function::auto_accessor::parse::{{closure}}
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/mod.rs:37:13
  13: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/adapters/map.rs:96:28
  14: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2409:21
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/adapters/map.rs:122:9
  16: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/adapters/mod.rs:201:9
  17: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2471:9
  18: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/adapters/mod.rs:184:14
  19: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/mod.rs:2988:35
  20: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/spec_extend.rs:17:9
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/spec_from_iter.rs:33:9
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/mod.rs:2894:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2003:9
  25: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1935:51
  26: core::iter::adapters::try_process
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/adapters/mod.rs:170:17
  27: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1935:9
  28: core::iter::traits::iterator::Iterator::collect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2003:9
  29: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::function::auto_accessor::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/mod.rs:34:17
  30: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::function::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/function/mod.rs:24:9
  31: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parser::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/parser/mod.rs:68:35
  32: lib_flutter_rust_bridge_codegen::library::codegen::parser::mir::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mir/mod.rs:17:16
  33: lib_flutter_rust_bridge_codegen::library::codegen::parser::parse_inner
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mod.rs:50:20
  34: lib_flutter_rust_bridge_codegen::library::codegen::parser::parse
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/parser/mod.rs:20:5
  35: lib_flutter_rust_bridge_codegen::library::codegen::generate_once
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/mod.rs:50:20
  36: lib_flutter_rust_bridge_codegen::library::codegen::generate::{{closure}}
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/mod.rs:34:9
  37: lib_flutter_rust_bridge_codegen::library::codegen::controller::run
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/controller/mod.rs:23:9
  38: lib_flutter_rust_bridge_codegen::library::codegen::generate
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/library/codegen/mod.rs:33:5
  39: flutter_rust_bridge_codegen::main_given_cli
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/main.rs:29:13
  40: flutter_rust_bridge_codegen::main
             at /home/stefan/gitrepos/flutter_rust_bridge/frb_codegen/src/main.rs:19:5
  41: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  43: std::rt::lang_start::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  44: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
  45: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  46: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  47: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  48: std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
  49: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  50: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  51: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  52: std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  53: std::rt::lang_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  54: main
  55: <unknown>
  56: __libc_start_main
  57: _start)
```
Into exile, I must go. Failed, I have.

**Comment by fzyzcjy** [comment]
For that `FrbOpaqueSyncReturnTwinMoi` error, it seems CI is green on master, so maybe try to merge latest master.

> Into exile, I must go. Failed, I have.

What happened?? I searched this sentence and seems to be a quote, but I am not sure so still worried, are you OK, you don't really exile right?

**Comment by TrackerSB** [comment]
Don't worry! I closed the PR since I switched to sticking to NaiveDateTime instead of NaiveDate.
Do you know Star Wars? It's i citation from Yoda (https://www.quotes.net/mquote/91299).

**Pull request closed without merging**
