### PR TITLE
Support for Web Debugging

### LINKED ISSUE #1002: [Bug] Debug Mode with Web target
### Describe the bug

flutter_rust_bridge works when run in profile or release mode on the Web, but not in debug mode. This means that there's no debugging and no hot reload on that target, which makes it pretty much impossible to develop.

The `serve` utility also only runs in profile and release. I'm currently trying to implement my own solution that allows debugging, but I'm running into problems left right and center.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
n/a
```

### To Reproduce

I created a simple proxy in Rust for serving the Flutter code with the right HTTP headers:

```rust
use std::str::FromStr;

use warp::{
    http::HeaderValue,
    hyper::{
        header::{
            HeaderName, ACCESS_CONTROL_ALLOW_CREDENTIALS, ACCESS_CONTROL_ALLOW_HEADERS,
            ACCESS_CONTROL_ALLOW_ORIGIN,
        },
        Body, Response,
    },
    Filter, Rejection, Reply,
};
use warp_reverse_proxy::reverse_proxy_filter;

async fn add_headers(mut response: Response<Body>) -> Result<impl Reply, Rejection> {
    let headers = response.headers_mut();
    headers.insert(
        ACCESS_CONTROL_ALLOW_ORIGIN,
        HeaderValue::from_str("http://localhost:3000").unwrap(),
    );
    headers.insert(
        ACCESS_CONTROL_ALLOW_CREDENTIALS,
        HeaderValue::from_str("true").unwrap(),
    );
    headers.insert(
        ACCESS_CONTROL_ALLOW_HEADERS,
        HeaderValue::from_str("content-type, accept, authorization").unwrap(),
    );
    headers.insert(
        HeaderName::from_str("cross-origin-opener-policy").unwrap(),
        HeaderValue::from_str("same-origin").unwrap(),
    );
    headers.insert(
        HeaderName::from_str("cross-origin-embedder-policy").unwrap(),
        HeaderValue::from_str("require-corp").unwrap(),
    );

    Ok(response)
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    warp::serve(
        reverse_proxy_filter("".to_owned(), "http://localhost:3001".to_owned())
            .and_then(add_headers),
    )
    .run(([127, 0, 0, 1], 3000))
    .await;

    Ok(())
}
```

Then in `index.html`, I have to change the websocket URL and load canvaskit from a local path:

```js
    Object.defineProperty(window, "$dwdsDevHandlerPath", {
      value: 'ws://localhost:3001/$dwdsSseHandler',
      writable: false
    });
    window.addEventListener('load', function (ev) {
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: async function (engineInitializer) {
          const appRunner = await engineInitializer.initializeEngine({
            canvasKitBaseUrl: '/canvaskit/',
          });
          appRunner.runApp();
        }
      });
    });
```

Then I have to update the launch configuration of vsc:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "myapp",
            "request": "launch",
            "type": "dart",
            "args": [
                "--web-port",
                "3001",
                "--web-launch-url",
                "http://localhost:3000"
            ]
        }
    ]
}
```

My loader code:

```dart
import 'dart:async';
import 'dart:html';
import 'dart:js_util';

// all generated imports here

const root = 'pkg/myapp';

@JS('wasm_bindgen')
external Object Function(String) get _noModules;

FutureOr<AssetManagerStorage> load() async {
  if (crossOriginIsolated != true) {
    return Future.error(const MissingHeaderException());
  }

  eval('window.wasm_bindgen = wasm_bindgen');
  final module = _noModules('${root}_bg.wasm');

  final module2 = await promiseToFuture<NativeWasmModule>(module);
  try {
    return NativeImpl(module2 as ExternalLibrary);
  } catch (e) {
    print('Wasm failed: $e');
    rethrow;
  }
}
```

This is the error  I get (from the `catch` above):

```
Wasm failed: Expected a value of type 'FutureOr<WasmModule>', but got one of type 'LegacyJavaScriptObject'
```

My research indicates that this might be caused by the `@JS` and `@anonymous` annotations of the `NativeWasmModule` class not being from `package:js`, but being homebrewn inside flutter_rust_bridge. The official annotations with the same name are used by the Dart compiler to do typecasts differently (according to the documentation, I haven't found the code for that yet), so this might be the reason why it can't cast a `JsObject` (which is the superclass of `LegacyJavaScriptObject`) to an `anonymous` class, which should work fine, according to the Dart documentation.

### Expected behavior

Everything runs fine without exceptions.

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

1.61.1 (with my PRs applied)

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2364], locale en-AT)
    • Flutter version 3.7.0 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at C:\Users\micro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anlumo**
Fixes #1002

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [X] The code generator is run and the code is formatted (e.g. via `just refresh_all`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

Note that this is a breaking change! The API for the Web platform is slightly different.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
The feature (web debugging) looks interesting! cc @Desdaemon who implemented the great web part

**Comment by fzyzcjy** [comment]
For future readers of this PR: Some explanations are in https://github.com/fzyzcjy/flutter_rust_bridge/issues/1002#issuecomment-1410951001

**Comment by harryfei** [comment]
Wise this can be merged.

**Comment by satvikpendem** [comment]
Can this still be merged? It doesn't look like the CI have fundamental errors.

**Comment by fzyzcjy** [comment]
> @satvikpendem Can this still be merged? It doesn't look like the CI have fundamental errors.

As long as CI goes green, and I made a review about it (usually only need to change some uber-nit things after review), it is ready for merge.

**Comment by anlumo** [comment]
The fundamental problem is that tests are required to be added to PRs, but since this is a fix for compile issues that don't happen in the way the tests are compiled, it's not possible.

**Comment by fzyzcjy** [comment]
Then the tests is not strictly needed in this case IMHO. It would be great to be added, but if impossible then it is OK

**Comment by satvikpendem** [comment]
So what's the next step for this one? Are there any CI errors that are not related to testing that need to be fixed?

**Comment by anlumo** [comment]
> So what's the next step for this one? Are there any CI errors that are not related to testing that need to be fixed?

It needs to be rebased to master and then the CI errors fixed (without breaking the feature again).

**Comment by anlumo** [comment]
Uh... 
image

**Comment by fzyzcjy** [comment]
Hmm... let me re-run it first

**Comment by anlumo** [comment]
I need to look into what that test actually does, because I have no idea what's happening.

**Comment by satvikpendem** [comment]
Unstale

**Comment by aran** [comment]
Any chance of seeing an updated CI run on this? Would be helpful to get this feature.

**Comment by fzyzcjy** [comment]
Feel free to fork this PR and fix it if the original author does not have time to fix CI!

**Comment by anlumo** [comment]
I just rebased the branch on top of master again, but it's untested. The new dependency on uuid 4.1 caused complete mayhem on my project, and I now have to rewrite a ton of stuff to get it to compile again.

**Comment by aran** [comment]
w.r.t. the reverse proxy in book/src/build_wasm.md, this can be simplified soon through a new `--web-header` option to flutter run: https://github.com/flutter/flutter/pull/136297

**Comment by anlumo** [comment]
I'm running my own executor now that doesn't use web workers and thus I don't need SharedArrayBuffers and thus I don't need any special headers any more. My life is much simpler now.

**Comment by fzyzcjy** [comment]
> The new dependency on uuid 4.1 caused complete mayhem on my project, and I now have to rewrite a ton of stuff to get it to compile again.

Sad to hear that :/ If you like, you can use `dependency_overrides` in your own project to lock to an older uuid version

**Comment by satvikpendem** [comment]
Has anyone tried [rinf](https://github.com/cunarist/rinf) for web debugging? It says it supports web but just wondering if those interested in FRB have also tried that for web development.

**Comment by fzyzcjy** [comment]
IMHO this is supported in v2. Thank you all the same for the PR, and feel free to create an issue if it does not work in v2!

**Pull request closed without merging**
