### PR TITLE
Fix Issue [#2178] and Issue [#2167] #2187

### PR DESCRIPTION
**Pull request by Larpoux**
## Changes

_Please list issues fixed by this PR here, using format "Fixes #the-issue-number"._

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Looks great, the CI fails mainly maybe because your local Flutter version differs from the CI's.

To make CI green and avoid things related to that, one way is to not execute `./frb_internal precommit` (which by default touch everything), revert to previous commit, and 

* For lints, a quick auto fix command is `cargo clippy --fix --allow-dirty --allow-staged -- -D warnings && cargo +nightly fmt`, or alternatively manually check the CI error and change code
* For "Command Generate", can run `cargo run --manifest-path /path/to/flutter_rust_bridge/frb_codegen/Cargo.toml -- generate` on frb_example/integrate_third_party folder

Anyway you can ignore the lints thing and I can do that if your env is somehow not working, and just run the latter generate thing

**Comment by Larpoux** [comment]
Thanks for the informations. I am going to try to set correctly my dev env. I would like to be able to submit a clean/green Pull Request.

**Comment by fzyzcjy** [comment]
In addition, the `precommit` is indeed quite slow since it runs everything. Thus, for normal development, it is better to run single commands like I mentioned above, which is faster since only run one thing per command.

**Comment by Larpoux** [comment]
Retry with flutter 3.22.0-0.2.pre

**Pull request closed without merging**
