### PR TITLE
Pool and cancellable

### PR DESCRIPTION
**Pull request by lattice0**
merge new stuff + `pub struct CancelTokenHandle(pub i64, pub i64)` compiles.

I'm unsure of what `nativeVisionUtils` should be. Perhaps you forgot to put the code for it? Also there's no `CancelTokenHandle`

### CODE REVIEW

**Comment by lattice0** [comment]
@fzyzcjy I believe you meant for

```rust
pub fn cancel_token_new(sub_pool_id: i64) -> Result<CancelTokenHandle> {
    Ok(CancelTokenHandle::get_pool().put_object(sub_pool_id, Arc::new(CancelToken::new())))
}

pub fn cancel_token_cancel(cancel_token: CancelTokenHandle) -> Result<()> {
    let cancel_token = CancelTokenHandle::get_pool().get_cloned_object(cancel_token)?;
    cancel_token.cancel();
    Ok(())
}

pub fn cancel_token_remove(cancel_token: CancelTokenHandle) -> Result<()> {
    CancelTokenHandle::get_pool().remove_object(cancel_token);
    Ok(())
}
```

to be callable from Dart like on here:

 ```dart
 static Future<FrbCancelableFuture<R>> create<R>({
    required int subPoolId,
    required FrbCancelableFutureRunner<R> runner,
  }) async {
    final ans = FrbCancelableFuture<R>._(
        await nativeVisionUtils.cancelTokenNew(subPoolId: subPoolId));
    unawaited(ans._run(runner));
    return ans;
  }
```

This is not in the `api.rs`, but I guess it should be there so code is generated for it?

**Comment by fzyzcjy** [comment]
Nice try! The main problem is described here: https://github.com/fzyzcjy/flutter_rust_bridge/pull/333#issuecomment-1037079219. So may I know your plan to solve it?

**Comment by lattice0** [comment]
problem https://github.com/fzyzcjy/flutter_rust_bridge/pull/333#issuecomment-1037079219 didn't bother me. I though of creating a macro that generates this stuff: 

`cancel_tokenize!(CancelTokenHandle);`

The problem is on the dart side:

```
static Future<FrbCancelableFuture<R>> create<R>({
   required int subPoolId,
   required FrbCancelableFutureRunner<R> runner,
 }) async {
   final ans = FrbCancelableFuture<R>._(
       await nativeVisionUtils.cancelTokenNew(subPoolId: subPoolId));
   unawaited(ans._run(runner));
   return ans;
 }
```

like, what would `nativeVisionUtils` be?

**Comment by fzyzcjy** [comment]
> like, what would nativeVisionUtils be?

nativeVisionUtils is indeed nothing but the auto-generated dart things from api.rs.

That is (part of) the problem - if we put these code in frb_dart, we do not have access to the auto-generated dart code.

One approach may be, we can do something like (rough draft, just random naming to show rough idea):

```
// frb_dart

abstract class FrbCancelTokenApiInterface {
  cancelTokenNew(int subpoolid);
}

static Future<FrbCancelableFuture<R>> create<R>({
  required FrbCancelTokenApiInterface api,
   required int subPoolId,
   required FrbCancelableFutureRunner<R> runner,
 }) async {
   final ans = FrbCancelableFuture<R>._(
       await api.cancelTokenNew(subPoolId: subPoolId));
   unawaited(ans._run(runner));
   return ans;
 }
```

```
// user's code

// or, we can provide a flag to automatically inject `implemets FrbCancelTokenApiInterface` in the [generated code](https://github.com/fzyzcjy/flutter_rust_bridge/blob/d1097eae26f1bed4231945062cdad142b28f645e/frb_example/pure_dart/dart/lib/bridge_generated.dart#L18)
class MyApi extends FlutterRustBridgeExample implements FrbCancelTokenApiInterface {}

create(api: myapi, ...)
```

**Pull request closed without merging**
