### PR TITLE
Web support

### PR DESCRIPTION
**Pull request by Desdaemon**
New flag `--wasm` with some functionality:
- WASM-specific implementation file
- Acts as if `--dart-decl-output` is specified, fallback path is used if not supplied by user

See #315.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
👀

**Comment by Desdaemon** [comment]
This PR might have to be split soon to address the issue of shimming threads and ReceivePorts for web.

**Comment by Desdaemon** [comment]
It's been a while, but there should be a better way to do this now. Here's a sneak peek.

Screen Shot 2022-07-17 at 23 42 30

**Comment by fzyzcjy** [comment]
Has that been implemented? Looking forward to it!

**Comment by Desdaemon** [comment]
It's not merged yet, but it mainly revolves around spawning web workers.

**Pull request closed without merging**
