### PR TITLE
Allow ffigen 10.x

### LINKED ISSUE #1429: [Bug] Should allow ffigen 10.x
### Describe the bug

frb's ffigen version validation requires ffigen <=9. ffigen 10.0.0 has been released https://pub.dev/packages/ffigen/changelog#1000 and should be supported

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aran**
Allow ffigen 10.x in commands.rs validation.
Update pubspec.yaml files and respective .lock files. Changes in frb_example/pure_dart_multi/dart/lib/ are due to `just rust_build_and_test`.

Fixes #1429

## Changes

Fixes #1429

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [N/A] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [N/A] The code generator is run and the code is formatted (via `just precommit`).
- [N/A] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
CI seems failing, I will merge after it is green!

In the meantime, I need to say that I am developing FRB 2.0 and will hopefully release within a week, with overhaul of the codebase. Therefore, an alternative way is to wait until FRB 2.0 and do the change. But it depends on you, I am also OK to get this merged, and then I manually merge to FRB 2.0 (but may do some duplicated work)

**Comment by aran** [comment]
Looks like this can't be done until 3.16.3 is released, because of the `file` dependency at https://github.com/flutter/flutter/blob/3.16.2/packages/integration_test/pubspec.yaml.

**Comment by fzyzcjy** [comment]
I see, then we may just wait a bit :)

**Comment by erdemyerebasmaz** [comment]
> Looks like this can't be done until 3.16.3 is released, because of the `file` dependency at https://github.com/flutter/flutter/blob/3.16.2/packages/integration_test/pubspec.yaml.

[Flutter 3.16.3 is released](https://groups.google.com/g/flutter-announce/c/2n1fVrZm8KY/m/uNwdodKqAwAJ)

**Comment by erdemyerebasmaz** [comment]
> Looks like this can't be done until 3.16.3 is released, because of the `file` dependency at https://github.com/flutter/flutter/blob/3.16.2/packages/integration_test/pubspec.yaml.

[Flutter 3.16.3 is released](https://groups.google.com/g/flutter-announce/c/2n1fVrZm8KY/m/uNwdodKqAwAJ)

**Comment by fzyzcjy** [comment]
Then I guess we will not be able to get 10.x within ~3mo... Because Flutter release stable versions roughly on 3 months, and IIRC it officially does not suggest people to use beta on production.

**Comment by fzyzcjy** [comment]
Since we need to wait, I temporarily convert it to github's "draft" status. Feel free to convert it back later!

**Comment by aran** [comment]
ffigen 11 is out now. It might be best to wait for flutter to unlock the higher version then see where ffigen is at that time, or find another approach within frb to avoid the need for these PRs.

**Comment by fzyzcjy** [comment]
Looks reasonable!

**Comment by erdemyerebasmaz** [comment]
@fzyzcjy @aran Update: Flutter 3.19 has been released to stable channel yesterday.

**Comment by fzyzcjy** [comment]
I see it a few hours ago! Feel free to PR to support 10.x, alternatively I will implement it in the next batch (hopefully within several days / a week)

**Pull request closed without merging**
