### PR TITLE
Petty automatic updates

### PR DESCRIPTION
**Pull request by coder0xff**
## Changes

When running tests, linting, etc, some files are automatically modified by tooling. Rather than locally reverting them over and over or just ignoring them, I figured I'd make a PR to roll them up.

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (via `just precommit`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by coder0xff** [comment]
@fzyzcjy It looks like `pub get` is coming to a different conclusion on my computer than it is in CI? Any idea what's going on there?

**Comment by fzyzcjy** [comment]
Hmm what's your local flutter version? (`flutter --version`). And check the version in CI.

Btw would be great to setup `fvm`, so everyone is in the same version automatically

**Comment by fzyzcjy** [comment]
Ha it is 0 line of change now!

image

**Comment by coder0xff** [comment]
> Ha it is 0 line of change now!
> 
> image

Yeah, didn't know if you want the chmod +x. If not this can be closed.

**Comment by fzyzcjy** [comment]
Oh I did not realize that since I just look at the github page :) If there is this change, surely it can be merged.

**Comment by fzyzcjy** [comment]
Oh I see, it is there ;)

(Btw I guess github should somehow notify this in the headline, e.g. "+2files-2files")

image

**Pull request merged**
