### PR TITLE
feat: mock mode

### LINKED ISSUE #2247: Cannot mock RustLib without loading FFI
### Describe the bug

Following the instructions in https://cjycode.com/flutter_rust_bridge/guides/how-to/test
does not work.

I get the following error:

```text
Invalid argument(s): Failed to load dynamic library 'rhttp.dll': error code 126
  dart:ffi                                                                new DynamicLibrary.open
  package:flutter_rust_bridge/src/platform_types/_io.dart 42:47           new ExternalLibrary.open
  package:flutter_rust_bridge/src/loader/_io.dart 62:46                   loadExternalLibraryRaw.<fn>
  package:flutter_rust_bridge/src/loader/_io.dart 49:22                   loadExternalLibraryRaw.tryAssumingNonPackaged
  package:flutter_rust_bridge/src/loader/_io.dart 61:12                   loadExternalLibraryRaw
  package:flutter_rust_bridge/src/loader/_io.dart 14:10                   loadExternalLibrary
  package:flutter_rust_bridge/src/main_components/entrypoint.dart 129:13  BaseEntrypoint._loadDefaultExternalLibrary
  package:flutter_rust_bridge/src/main_components/entrypoint.dart 48:31   BaseEntrypoint.initImpl
  package:rhttp/src/rust/frb_generated.dart 30:20                         RustLib.init
```

### Steps to reproduce

Follow instructions in https://cjycode.com/flutter_rust_bridge/guides/how-to/test

### Logs

```shell
Should not be needed
```

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Windows 11

### Version of `flutter_rust_bridge_codegen`

2.1.0

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tienisto**
## Changes

Fixes #2247.

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! Some nits

1. I am wondering, for user-facing API, whether we should make it a separate function `initMock`, or the same function with an extra arg `init({..., bool mock})`?
2. To fix CI, try `./frb_internal precommit-generate` (which takes at least several minutes to run since it runs codegen in debug mode for many folders)

**Comment by Tienisto** [comment]
Thanks for the quick response!

Actually, I had it like `init({..., bool mock})` originally. However, I thought it would be unclear what parameters are used and I didn't like that `api` is optional while it is not when `mock` is `true`.
A separate function would be more type safe in this case.
I am fine with both solutions though.

**Comment by fzyzcjy** [comment]
You are welcome!

> However, I thought it would be unclear what parameters are used and I didn't like that api is optional while it is not when mock is true.
A separate function would be more type safe in this case.

Looks pretty reasonable.

> I've run ./frb_internal precommit-generate but it doesn't seem to fix all issues. Do you know what's missing?

Looks like need to edit https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_codegen/assets/integration_template/shared (e.g. copy-paste/modify things according to the CI hint) which is the template

**Comment by Tienisto** [comment]
Thanks! I am currently not at home so feel free to add it. Otherwise, I will add it tomorrow

**Comment by fzyzcjy** [comment]
@all-contributors please add @Tienisto for code

**Comment by fzyzcjy** [comment]
@Tienisto Looks like codecov is unhappy (see below). Maybe we can add a few lines in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/test/mockability_test.dart to test this code path.

image


https://app.codecov.io/gh/fzyzcjy/flutter_rust_bridge/commit/c5bdedbbb1b222162bdc88d28e96313b687007a8

image

**Pull request merged**
