### PR TITLE
Improve CI and fix #1174

### LINKED ISSUE #1174: ci: codegen call dart_test_web_integration take too long time
1. from
https://github.com/fzyzcjy/flutter_rust_bridge/blob/b45ae48c16d709b194c0ba79354e2c59805f87b2/frb_codegen/src/main.rs

there are two test, please split it in ci.yaml.
2. android run on macos, please run on ubuntu
```yaml
flutter_test_android:
    name: Flutter integration test on Android
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel"
          - "Nexus 6"
      fail-fast: false
```

### PR DESCRIPTION
**Pull request by huang12zheng**
## Changes

_Please list issues fixed by this PR here, using format "Fixes #the-issue-number"._

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (via `just precommit`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by huang12zheng** [comment]
now, nerve waiting for macos.

**Comment by huang12zheng** [comment]
ping @fzyzcjy  please check and I would do anothor pr  do handle something about chche

**Review by fzyzcjy — APPROVED** [review]
Coming! Looks like ci.yaml has minor changes due to #1172. After resolving conflicts, I am ready to merge :)

**Comment by huang12zheng** [comment]
ping @fzyzcjy

**Pull request merged**
