### PR TITLE
reproduce #549

### PR DESCRIPTION
**Pull request by TENX-S**

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Btw in your local environment, try to upgrade ffigen to 6.x and frb to latest and retry to see whether it still happens

**Comment by TENX-S** [comment]
"invalid assignment" has gone after upgrade ffigen to 6.0.1.
But we got a new one :(
Screen Shot 2022-07-07 at 16 44 33

**Comment by fzyzcjy** [comment]
upgrade your frb *dart* dependency

**Comment by TENX-S** [comment]
Problem solved. Thanks for your time!

**Comment by fzyzcjy** [comment]
You are welcome!

**Pull request closed without merging**
