### PR TITLE
Add support of `Vec<bool>`

### LINKED ISSUE #801: [Bug] vec<bool> not supported
### Describe the bug

I found out that `Vec<bool>` is not supported, when having the following function included in my `api.rs`.
```rust
pub fn write_foo(basis_events: Vec<Foo>) -> anyhow::Result<Vec<bool>> {
    ***
}
```

This is the function as when I replace it it starts to work. Is this a bug or a missing feature?
```rust
pub fn write_foo(foo_events: Vec<Foo>) -> anyhow::Result<bool> {
    ***
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
PS C:\Users\alexp\foo> $env:RUST_BACKTRACE = 'debug'; flutter_rust_bridge_codegen --rust-input v12\src\api.rs --dart-output .\lib\bridge_generated.dart --dart-decl-output .\lib\bri
dge_definitions.dart
[2022-10-23T23:22:17Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried \\?\C:\Users\alexp\Basis\basis-hybrid\v12\src\io.rs, \\?\C:\Users\alexp\foo\v12\src\io\mod.rs, \\?\C:\Users\alexp\foo\v12\src\bridge_generated\io.rs, \\?\C:\Users\alexp\foo\v12\src\bridge_generated\io\mod.rs, )
thread 'main' panicked at 'does not support Bool yet', C:\Users\alexp\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.49.0\src\ir\ty_primitive_list.rs:31:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

I simplified most of the stuff to foo

### PR DESCRIPTION
**Pull request by NightFeather0615**
## Changes

Fixes #801
~~Blocked by sunshine-protocol/allo-isolate#47 (merged, awaiting publish)~~

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (via `just precommit`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by NightFeather0615** [comment]
I'm not sure this is the right way to do it.

I edited the [code](https://github.com/NightFeather0615/flutter_rust_bridge/blob/ad9d1314a69a3399daff2c62c580fe86beec3ccc/frb_codegen/src/parser/ty.rs#L379-L389) for the `PrimitiveList` parser so that `Vec<bool>` was parsed as a `GeneralList`.

After doing this, I noticed that Vec<bool> did not implement the `IntoDart` trait, so I forked and [edited](https://github.com/NightFeather0615/allo-isolate/blob/1cd502fdd8a9b70c5eb03c53e8f2b51e6bd721ca/src/into_dart.rs#L104) the `allo-isolate` library so that the `bool` implements the `IntoDartExceptPrimitive` trait.

If this is the right way to solve the problem, I can open a new PR on `allo-isolate`.

Sorry for bad English, please leave a comment if anything is not clear.

**Comment by NightFeather0615** [comment]
And the web part seems to be broken, I'll try to fix it later on.

**Comment by fzyzcjy** [comment]
Looks good! I do not have much time for review now, but the general idea is to mimic existing things. For example, one way is to mimic how is `Vec<u8>, Vec<i8>, Vec<i32>...` implemented.

Another way, mentioned in https://github.com/fzyzcjy/flutter_rust_bridge/issues/801#issuecomment-1288231337, is "when seeing Vec bool, categorize it as IRGeneralList, not IRPrimitiveList, in the parser"

**Comment by fzyzcjy** [comment]
Looks good! I do not have much time for review now, but the general approach looks acceptable. Not checked yet whether PR to allo-isolate is necessary or not, but if you find it is needed and reasonable, feel free to PR! When implementing frb, we have already added many things to allo-isolate.

**Comment by NightFeather0615** [comment]
Thanks for reply! I seem to have successfully fixed `Vec<bool>` for `web` 🥳.
I will open new PR at `allo-isolate` later on.

By the way, is it normal for the `Dart test with Valgrind` and `Dart linter` CI tests to fail?

**Comment by fzyzcjy** [comment]
Good job! I will review once CI is green (except for known CI failures) and upstream PR is merged

**Comment by NightFeather0615** [comment]
@fzyzcjy I think most of it is done, some tests fail but I can't find out why, can you help me locate the problem?

By the way, I edited `justfile` to make the `sed` command work on Linux ([`-i` only accepts empty strings on macOS](https://stackoverflow.com/a/57766728/16278234)), let me know if I should create a new PR for this 😄.

**Comment by fzyzcjy** [comment]
let me rerun jobs first (IIRC two are expected but the third is a new thing)

**Comment by fzyzcjy** [comment]
I will review soon!

**Comment by NightFeather0615** [comment]
No problem, take your time!

**Comment by NightFeather0615** [comment]
I'm wondering if the cause of the Windows integration test build error is the same as this issue?
flutter/flutter#85143

**Review by fzyzcjy — APPROVED** [review]
Good job, LGTM!

**Comment by fzyzcjy** [comment]
The windows error does not seem related to this PR, so let me just merge the PR and resolve it later

**Comment by NightFeather0615** [comment]
Thanks for maintaining this awesome project!

And thanks to @HTGAzureX1212 for help me locate the problem 😄.

**Comment by fzyzcjy** [comment]
@all-contributors please add @NightFeather0615 for code

**Pull request merged**
