### PR TITLE
Doc for generation with multiple blocks of Api

### PR DESCRIPTION
**Pull request by dbsxdbsx**
## what's new 
Mention the new  example in Section `3.Features`.
Add a new doc for detailed explanation on why and how to generate Api within multiple blocks(files).

## related pr
https://github.com/fzyzcjy/flutter_rust_bridge/pull/516
https://github.com/fzyzcjy/flutter_rust_bridge/pull/527

## related issue
https://github.com/fzyzcjy/flutter_rust_bridge/issues/511

### CODE REVIEW

**Comment by fzyzcjy** [comment]
@all-contributors please add @dbsxdbsx for doc

**Comment by fzyzcjy** [comment]
Good work! LGTM, except some phrasing, which I will modify after merging.

**Comment by fzyzcjy** [comment]
Btw, https://app.grammarly.com is quite helpful to check and improve grammar automatically.

**Comment by fzyzcjy** [comment]
what is explicit and implicit api?

**Comment by dbsxdbsx** [comment]
> what is explicit and implicit api?

If API is defined by users, it is explicit, others like `new_uint8_list` are implicit API. Frb would throw panic with conflict on explicit API, but no warning but automatically add suffix starting from 0 to avoid implicit API conflict.

**Comment by fzyzcjy** [comment]
Ah, those are in the code details and I also do not remember very clearly currently. 

I guess it is by simple string manipulation without fancy data structures.

Feel free to refactor them!

**Comment by Desdaemon** [comment]
Great writeup @dbsxdbsx. I'm thinking whether it would be fruitful to pursue a crate-wide, explicit declaration process a la wasm_bindgen, which could solve a lot of the problems described here.

**Comment by dbsxdbsx** [comment]
> Great writeup @dbsxdbsx. I'm thinking whether it would be fruitful to pursue a crate-wide, explicit declaration process a la wasm_bindgen, which could solve a lot of the problems described here.

I have no idea what "a crate-wide, explicit declaration process" means here. But I guess it is something related to support for the web platform, right?

**Comment by fzyzcjy** [comment]
I am not sure, I guess it may be another toml configuration file specifying things instead of using command-line?

**Pull request merged**
