### PR TITLE
chore: downgrade rust version in frb_codegen

### PR DESCRIPTION
**Pull request by Integral-Tech**
## Changes

_Please list issues fixed by this PR here, using format "Fixes #the-issue-number"._

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [x] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by Integral-Tech** [comment]
Note: Rust version can't be reverted to the previous `1.74.0`
```
error: current MSRV (Minimum Supported Rust Version) is `1.74.0` but this item is stable since `1.76.0`
  --> frb_codegen/src/library/commands/cbindgen.rs:75:77
   |
75 |       let bindings = cbindgen::generate_with_config(parsed_crate_dir, config).inspect_err(|e| {
   |  _____________________________________________________________________________^
76 | |         // This will stop the whole generator and tell the users, so we do not care about testing it
77 | |         // frb-coverage:ignore-start
78 | |         if let Error::ParseSyntaxError { src_path, .. } = &e {
...  |
83 | |         // frb-coverage:ignore-end
84 | |     })?;
   | |______^
   |
```

**Comment by fzyzcjy** [comment]
> Note: Rust version can't be reverted to the previous 1.74.0

Hmm, then what about we use 1.74.0 and do not use inspect_error?

**Comment by Integral-Tech** [comment]
> > Note: Rust version can't be reverted to the previous 1.74.0
> 
> Hmm, then what about we use 1.74.0 and do not use inspect_error?

Using `inspect_err` here can't pass the lint check of Rust 1.83.0.

**Comment by fzyzcjy** [comment]
Hmm, what about suppressing this lint at this place (`#[allow(...)]` on this line), with a line of comment saying we can do this after bumping rust-version in the future

**Review by fzyzcjy — APPROVED** [review]

**Pull request merged**
