### PR TITLE
ci: support concurrency

### PR DESCRIPTION
**Pull request by huang12zheng**
inspire from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency:~:text=%E4%B8%BA%E8%BF%90%E8%A1%8C%E5%AE%9A%E4%B9%89%E3%80%82-,concurrency%3A%0A%20%20group%3A%20%24%7B%7B%20github.head_ref%20%7C%7C%20github.run_id%20%7D%7D%0A%20%20cancel%2Din%2Dprogress%3A%20true,-%E7%A4%BA%E4%BE%8B%EF%BC%9A%E4%BB%85%E5%8F%96%E6%B6%88

and 
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Oops sorry, originally thought WIP == draft, but later realize draft will cancel Github ci...

**Comment by huang12zheng** [comment]
I'm just trying. I need a review. I'll let you know.

**Comment by huang12zheng** [comment]
Unfortunately, workflow cancels the job because there is no matrix property on GitHub.
@fzyzcjy

**Comment by fzyzcjy** [comment]
hmm :/

**Comment by fzyzcjy** [comment]
btw you can keep the PR open, no worries

**Pull request closed without merging**
