### PR TITLE
Use @generated in files to follow rustfmt

### PR DESCRIPTION
**Pull request by atezet**
## Changes

Generated Rust files should include `@generated` in the first few lines. See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_generated_files

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [-] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [X] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [-] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! Ready to merge after CI is green :)

**Comment by fzyzcjy** [comment]
(For the last errors, I guess also just copy-paste and execute that patch. Looks like a spacing error)

**Comment by atezet** [comment]
Thanks! My editor removed some trailing whitespace. I'm not sure exactly why the trailing whitespace is generated, otherwise I'd prevent that instead, but I couldn't figure it out.

**Comment by fzyzcjy** [comment]
You are welcome!

> I'm not sure exactly why the trailing whitespace is generated

I guess it is because rust formatter does not auto remove it (kind of shortcoming I guess)...

**Comment by atezet** [comment]
Oops, reverted a bit too much!

**Comment by fzyzcjy** [comment]
@all-contributors please add @atezet for code

**Pull request merged**
