### PR TITLE
Bump Dart SDK to 2.15

### PR DESCRIPTION
**Pull request by ngasull**
Follows up on #882 more precisely [@fzyzcjy's suggestion](https://github.com/fzyzcjy/flutter_rust_bridge/pull/882#issuecomment-1355844249)

This bump is motivated by the use of [constructor tearoffs](https://medium.com/dartlang/dart-2-15-7e7a598e508a#9c16): passing constructor as a regular function.

It shouldn't be a major issue for FRB users considering that ffigen currenttly required sdk is 2.17.

### CODE REVIEW

**Review by fzyzcjy — APPROVED** [review]
LGTM once CI passes :)

**Comment by ngasull** [comment]
Is it me or ios CI randomly fails @fzyzcjy ? :upside_down_face:

**Comment by fzyzcjy** [comment]
the latter :)

**Comment by fzyzcjy** [comment]
@all-contributors please add @ngasull for code

**Pull request merged**
