### PR TITLE
Fix dashed library names

### PR DESCRIPTION
**Pull request by vhdirk**
## Changes

Rust library names can't have dashes, while the package name can. This fixes it. 

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good fix! After CI is green, i.e. fix the lint error -

```
error: single-character string constant used as pattern
   --> frb_codegen/src/library/codegen/config/internal_config_parser/generator_parser.rs:165:28
    |
165 |     Ok(target.name.replace("-", "_"))
    |                            ^^^ help: try using a `char` instead: `'-'`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
    = note: `-D clippy::single-char-pattern` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::single_char_pattern)]`
```

I am ready to merge it :)

**Comment by fzyzcjy** [comment]
Btw, for dashed library names, does the other part of flutter_rust_bridge work?

**Comment by vhdirk** [comment]
So far, I haven't encountered any other issues using a dashed crate name ¯\_(ツ)_/¯

**Comment by fzyzcjy** [comment]
Then that's great!

**Comment by fzyzcjy** [comment]
@all-contributors please add @vhdirk  for code

**Pull request merged**
