### PR TITLE
cleaned up `generate()` in `dart/mod.rs`

### PR DESCRIPTION
**Pull request by w-ensink**
- split the big function up into some smaller functions with descriptive names

Feedback is welcome 🙂

### CODE REVIEW

**Comment by fzyzcjy** [comment]
LGTM, good work :)

Btw CI is failing (though not due to this PR). Do you have interest in fixing it, such that after the CI passes I will merge this PR.

**Comment by w-ensink** [comment]
I would love to, but I can't really tell what went wrong on the CI, the errors are really vague... If I look at the commit history it started failing at a point when you just updated some docs, so it isn't really clear what is causing it to fail.

**Comment by fzyzcjy** [comment]
Yes. I suspect it is because, either Flutter upgrades, or GitHub Actions runtime upgrades.

Anyway, maybe fire an issue at proper places - StackOverflow / github issues of flutter.

> /Users/runner/hostedtoolcache/flutter/3.0.2-stable/x64/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/flutter/3.0.2-stable/x64/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
Error: Process completed with exit code 1.

**Comment by w-ensink** [comment]
Yeah, maybe GitHub started using M1 based Macs. I'll try installing rosetta before running the tests.

**Comment by fzyzcjy** [comment]
Btw you may use a shell command to print out "is this a x86 or M1 macos", so we will know exactly

**Comment by w-ensink** [comment]
Good point, but it seems like they are using `x86_64` still, since it says rosetta is not available on the system.

**Comment by fzyzcjy** [comment]
Great job!

**Pull request merged**
