### PR TITLE
Fix function generation related to opaque rust

### LINKED ISSUE #863: support `pub struct IDb(pub Opaque<Surreal<Db>>)`
I'm not sure if that mode is supported. Or how to support it

```rs
pub struct IDb(pub Opaque<Surreal<Db>>);
```
```dart
@sealed
class SurrealDb extends FrbOpaque {
  final Db bridge;
  SurrealDb.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueSurrealDb;  //  error

  @override
  ShareFnType get shareFn => bridge.shareOpaqueSurrealDb;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.SurrealDbFinalizer;
}

class IDb {
  final SurrealDb field0;

  IDb({
    required this.field0,
  });
}
```
* error
```
The getter 'shareOpaqueSurrealDb' isn't defined for the type 'Db'.
Try importing the library that defines 'shareOpaqueSurrealDb', correcting the name to the name of an existing getter, or defining a getter or field named 'shareOpaqueSurrealDb'.
```

### PR DESCRIPTION
**Pull request by rogurotus**
Fixes #863

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (e.g. via `just refresh_all`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

### CODE REVIEW

**Comment by rogurotus** [comment]
@fzyzcjy ping

**Comment by fzyzcjy** [comment]
Ah not sure why I did not get notification from "mark ready for review"... Reviewing!

**Review by fzyzcjy — COMMENTED** [review]
LGTM! except that we should add a test, otherwise the bug can regress one day

**Comment by fzyzcjy** [comment]
Good fix!

**Pull request merged**
