### PR TITLE
Fix CI and post_release GitHub actions

### LINKED ISSUE #1053: Fix CI and post_release GitHub actions
Given that the latest `just precommit` gives even different formatting from my machine and the CI... (Then I cannot publish new versions)

- [ ] just precommit
- [ ] ci
- [ ] post_release

### PR DESCRIPTION
**Pull request by fzyzcjy**
## Changes

Close #1053 

## Checklist

- [ ] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (via `just precommit`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
image

**Comment by huang12zheng** [comment]
@fzyzcjy Hi, can you tell me what 's mean about 'steps.checkout.outputs.rustc_hash'.
What is the possible value of rustc_hash?
I found that is ""
${{ runner.os }}-cargo-integrate-ios-${{ hashFiles('**/Cargo.lock') }}-${{ steps.checkout.outputs.rustc_hash }}
macOS-cargo-integrate-ios-f302defae6410775747c832675b999fd90184d549db782f8b6b7745acd60fb85-

**Comment by fzyzcjy** [comment]
@huang12zheng Hi, rustc_hash from which file?

**Comment by fzyzcjy** [comment]
Oh I see, you mean that cache part.

It should be documented in the github action in the "checkout" step

**Pull request merged**
