### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by ernstvanderlinden**
## Changes

_Please list issues fixed by this PR here, using format "Fixes #the-issue-number"._

## Checklist

- [ x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [ ] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator
Great project, thanks!

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Hi thanks for fixing typos! However, I guess "another" is not very wrong, because I want to say it is one other library. Btw, if you are interested in fixing typos in doc to improve reading, feel free to do so!

**Comment by GasinAn** [comment]
AI tells me that the old sentence do have a grammar mistake and the new one don't, because "another" can only be a determeter while "other" can be an adjective. And "Here is my other open-source library" do mean "这是我的另一个开源库". But it is so common for non-native English users to make this mistake.😂 I think this PR shall be merged.

**Comment by fzyzcjy** [comment]
Thanks!

**Comment by fzyzcjy** [comment]
(CI failure is unrelated; I will fix it separately)

**Comment by fzyzcjy** [comment]
@all-contributors please add ernstvanderlinden for doc

**Pull request merged**
