### PR TITLE
Support providing relative paths to configuration file

### LINKED ISSUE #2166: relative path to flutter_rust_bridge.yaml / rust_root is not working
### Describe the bug

Using a relative path, as in
```
› flutter_rust_bridge_codegen generate --config-file ../flutter_rust_bridge.yaml
```

fails with
```
Error: When compute_mod_from_rust_path(code_path="../app_core/src/application/bridge/frb_generated/mod.rs", base_dir="/Users/patmuk/code/own/sherry/system/sherry/app_core/src")

Caused by:
    prefix not found
```

This happens as well with other means of specifying a relative path, e.g. as rust_root in the flutter_rust_bridge.yaml or within an build.rs file.

### Steps to reproduce

› flutter_rust_bridge_codegen generate --config-file ../flutter_rust_bridge.yaml

### Logs

```shell
Error: When compute_mod_from_rust_path(code_path="../app_core/src/application/bridge/frb_generated/mod.rs", base_dir="/Users/patmuk/code/own/sherry/system/sherry/app_core/src")

Caused by:
    prefix not found
```
```


### Expected behavior

The base dir can be matched even if the path is relative.

### Generated binding code

_No response_

### OS

Sonoma 14.3.1.

### Version of `flutter_rust_bridge_codegen`

2.0.0.

### Flutter info

```shell
› flutter doctor -v                                                             
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/patmuk/code/own/sherry/system/sherry/.toolchain/flutter-local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /nix/store/4yaia9206kv08wp96zz51nf3fy4cnkrz-android-sdk-env/share/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /nix/store/4yaia9206kv08wp96zz51nf3fy4cnkrz-android-sdk-env/share/android-sdk
    • ANDROID_SDK_ROOT = /nix/store/4yaia9206kv08wp96zz51nf3fy4cnkrz-android-sdk-env/share/android-sdk
    • Java binary at: /nix/store/89mg4clgnz0hxakm1jn0qz7gzhbfva0v-zulu-ca-jdk-17.0.10/bin/java
    • Java version OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/patmuk/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 15 (mobile)              • D8014A3D-781A-4EC7-9113-3B50DF17BCAB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Version of `clang++`

_No response_

### Additional context

In my setup the rust folder is outside of the flutter folder, as in
```
/users/patmuk/code/myProject/rust
/users/patmuk/code/myProject/flutter
```
As a workaround I moved `flutter_rust_bridge.yaml` to `/users/patmuk/code/myProject/` (was in the flutter folder), and hid `build.rs`.

I assume that this can be fixed quite easily - but at the moment my time does not allow me to do so myself :(

### PR DESCRIPTION
**Pull request by patmuk**
## Changes
fixes #2166

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [ ] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Looks great! Maybe we can fix the CI by changing what it complains, e.g. 

```diff
diff --git a/frb_example/flutter_via_create/pubspec.lock b/frb_example/flutter_via_create/pubspec.lock
index eadc974..ad3f38c 100644
--- a/frb_example/flutter_via_create/pubspec.lock
+++ b/frb_example/flutter_via_create/pubspec.lock
@@ -297,10 +297,10 @@ packages:
     dependency: transitive
     description:
       name: web
-      sha256: d43c1d6b787bf0afad444700ae7f4db8827f701bc61c255ac8d328c6f4d52062
+      sha256: cd3543bd5798f6ad290ea73d210f423502e71900302dde696f8bff84bf89a1cb
       url: "https://pub.dev/"
     source: hosted
-    version: "1.0.0"
+    version: "1.1.0"
   webdriver:
     dependency: transitive
     description:
```

**Comment by patmuk** [comment]
Thanks :)
Yes - I have the same "problem" in my other PR. I think that locally the dependencies are getting updated, while on CI they are compared to the old once. Note that the `pubspec.yaml`  isn't changed - the new versions are still `valid`.
Thus it is very likely that a user's local system would update as well.

I think it would be best to use the new `pub spec.lock`s - but I did not look into the CI config to see how/why it compares with the old ones.

But I don't have a strong opinion on that, I could revert the pubspec.lock's to the older state as well.

**Comment by fzyzcjy** [comment]
> I think it would be best to use the new pub spec.locks - but I did not look into the CI config to see how/why it compares with the old ones.

Without detailed exploration, my first guess: because the flutter version is locked

**Comment by patmuk** [comment]
> > I think it would be best to use the new pub spec.locks - but I did not look into the CI config to see how/why it compares with the old ones.
> 
> Without detailed exploration, my first guess: because the flutter version is locked

Oh, that is very likely! I will revert the podspec.locks.

**Comment by fzyzcjy** [comment]
Yes I think so

**Pull request merged**
