### PR TITLE
feat: add preamble for dart generated files

### LINKED ISSUE #1948: custom ignore_for_file in generated dart file
**Is your feature request related to a problem? Please describe.**
Show too much lint messages in VSCode problem panel, if I had defined some strict lint rules in analysis_options.yaml.
Even if I add a exclude config in analysis_options.yaml, As soon as I open the generated code file in VSCode, the exclude option does not work and the lint error is displayed again.

**Describe the solution you'd like**
Add a config in `flutter_rust_bridge.yaml`, something like to the `preamble` config in [ffigen](https://github.com/dart-lang/native/blob/main/pkgs/ffigen/README.md)

<table>
<thead>
  <tr>
    <th>Key</th>
    <th>Explaination</th>
    <th>Example</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>preamble</td>
    <td>Raw header of the file, pasted as-it-is.</td>
    <td>

```yaml
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names
```

  </td>
</tr>
</tbody>

### PR DESCRIPTION
**Pull request by Krysl**
## Changes

Fixes #1948

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [x] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If @fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by Krysl** [comment]
I wrote it too hastily and added redundant parameters. I will clean them up.

**Comment by fzyzcjy** [comment]
Good job! To make CI pass (and if not want to run the too slow precommit), try `cd frb_codegen && UPDATE_GOLDENS=1  cargo test`. It would also be great to add a test, but since this is so trivial, I can put the tests there in the next batch.

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
No worries about the failed Web test - looks like flaky

**Comment by fzyzcjy** [comment]
To make a test, just add premable config in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/flutter_rust_bridge.yaml, and then run

```
./frb_internal generate-internal-frb-example-pure-dart
./frb_internal precommit-generate
```

**Comment by Krysl** [comment]
Sorry for late. the frb_internal test alwayse has some strange errors, and makes me a little impatient.

> To make a test, just add premable config in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/flutter_rust_bridge.yaml, ...

I've already tried adding a line of configuration there before, but the test didn't report any errors, and obviously there wasn't any verification of the generated code. Maybe I'm wrong?

**Comment by Krysl** [comment]
Adding one line of preamble  affects hundreds of files...
Should I commit these changes?

**Comment by fzyzcjy** [comment]
Anyway, then let me do it, no worries!

**Comment by Krysl** [comment]
Sorry, I'm too slow.
I add some test in `frb_codegen\test_fixtures\library\codegen\generator\api_dart\mod\simple`
Hope this is the right place for test.

**Comment by fzyzcjy** [comment]
Well, no need to be in there IMHO - just add premable config in [master/frb_example/pure_dart/flutter_rust_bridge.yaml](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/flutter_rust_bridge.yaml?rgh-link-date=2024-05-18T05%3A53%3A51Z). 

> Adding one line of preamble affects hundreds of generated files in pure_dart and pure_dart_pde...

I am not sure what happened, but the generated code will only contain a few lines of change (the new header). Maybe it is because of failure of text formatting etc?

**Comment by Krysl** [comment]
Well, it's your code base. If you think it's acceptable, then I'll do as you say.

> Maybe it is because of failure of text formatting etc?

No  text formatting issues. (It's just that I don't like that such a simple patch affects so many files.)

**Comment by fzyzcjy** [comment]
> If you think it's acceptable, then I'll do as you say.
> affects hundreds of generated files in pure_dart and pure_dart_pde...
> No text formatting issues. (It's just that I don't like that such a simple patch affects so many files.)

Oh I see! Then your simple test looks totally reasonable. I originally thought you meant some bugs in codegen.

**Comment by fzyzcjy** [comment]
@all-contributors please add @Krysl for code

**Pull request merged**
