### PR TITLE
Fix grammar in advantages.svg

### PR DESCRIPTION
**Pull request by adsouza**
The correct noun form for powerful is actually just power, which is the root. Similarly, the noun form of simple is simplicity.

## Changes

There's no PR for this because it's merely a minor edit to the text of an image.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Thank you for the change! Totally agree it should be simplicity, not simpleness.

As for powerfulness, I am not very sure: `power` (https://dictionary.cambridge.org/dictionary/english/power) seems to commonly refer to "ability to control people and events" or "the amount of political control a person or group has in a country", while I definitely do not want to control anyone! So I choose the less-common powerfulness.

**Comment by adsouza** [comment]
I don't want to argue over this but I'll leave you with one suggestion: take a look at the results of https://www.google.com/search?q=%22expressive+power%22 & see if that changes your mind at all.

**Comment by fzyzcjy** [comment]
Thank you! I know power has that meaning (at least dict says so) :) I am just worried if I use "power" without things like "expressive"... Anyway I will also consult my friend focusing on this area as well.

**Comment by fzyzcjy** [comment]
@all-contributors please add @adsouza for doc

**Pull request merged**
