### PR TITLE
Fix CI

### LINKED ISSUE #450: [Bug] CI fails (seemingly due to reasons that will not affect users - but anyway should fix it)
### Describe the bug

-

### Codegen logs with `RUST_LOG=debug` env variable

```shell
-
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sagudev**
Fixes #450

### CODE REVIEW

**Comment by sagudev** [comment]
@fzyzcjy could you rerun failing ci

**Comment by fzyzcjy** [comment]
Sure.

By the way, you can always make a dummy commit (e.g. change a line and then change back) to trigger ci

**Comment by sagudev** [comment]
On macOS there are seems to be an cargo error but there is no real error provided or it least I cannot read it. And those xcode and pods things are out of my knowledge.

**Comment by fzyzcjy** [comment]
for ios test the fix seems trivial given the error message:

```
               [+5764 ms] lib/main.dart:50:20: Error: 'Size' is imported from both 'dart:ffi' and 'dart:ui'.
               [   +3 ms]         imageSize: Size(width: 50, height: 50), zoomPoint: examplePoint, scale: generateScale(), numThreads: 4);
               [        ]                    ^^^^
               [   +4 ms] Target kernel_snapshot failed: Exception

**Comment by fzyzcjy** [comment]
I will check macos later.

**Comment by sagudev** [comment]
In CI we have checks to make sure that `with_flutter` and `pure_dart` **folders** have line length of 120 other files are standard 80. Changes in `justfile` now reflect that.

**Comment by sagudev** [comment]
> I will check macos later.

Apparently all is OK now.

**Comment by fzyzcjy** [comment]
Great work!

**Pull request merged**
