### PR TITLE
update all deps in locks

### PR DESCRIPTION
**Pull request by sagudev**
NOTE: https://github.com/sagudev/flutter_rust_bridge/runs/6277947055?check_suite_focus=true failed two times on my CI

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Sounds great. But the CI now seems to be failing, what about fixing it before merging

**Comment by fzyzcjy** [comment]
In addition, I wonder why you update those deps in locks? How is it related to fixing the failure you mentioned in your ci?

**Comment by sagudev** [comment]
I think current CI problems are from master. Its about `/pure_dart/dart/lib/bridge_generated.freezed.dart` which has nothing to do with my PR but its from previous commit:
slika
So its probably regression from: https://github.com/fzyzcjy/flutter_rust_bridge/pull/438.

As for my CI error, it's gone. Maybe it was just lottery.

**Comment by sagudev** [comment]
> In addition, I wonder why you update those deps in locks? How is it related to fixing the failure you mentioned in your ci?

I updated deps in lock because I noticed (by mistake) that they are outdated. No special reason. It's not related to fixing error on my CI but its rather causing it. But as I said before the failures were probably just random noise.

**Comment by fzyzcjy** [comment]
All right. So shall I merge it or not?

**Comment by sagudev** [comment]
It was really just a noise, it's working now on my fork: https://github.com/sagudev/flutter_rust_bridge/runs/6300502762?check_suite_focus=true

So I think you should merge it.

**Comment by fzyzcjy** [comment]
let me rerun it

image

**Comment by sagudev** [comment]
Did you fix errors in master?

**Comment by fzyzcjy** [comment]
Oh you are right, I will do that

**Comment by fzyzcjy** [comment]
Sorry, provided #446 I have to revert this...

**Comment by sagudev** [comment]
> Sorry, provided #446 I have to revert this...

Ah, no problem.

This locks are just for examples so they can be outdated without a harm.

**Pull request merged**
